### ISSUE TITLE
Scope of License

### ISSUE THREAD

**Issue by trathpai** [cleanlab/cleanlab#1020]
I wanted to clarify the license scope. Does the license apply when doing analytics work on internal dataset and using this dataset to train the models , these models eventually are used in commercial domain? Or does it apply when using cleanlab directly in a commercial product only?

**Comment by jwmueller** [comment]
Disclaimer: I am not a lawyer and not providing legal advice, you should have your own lawyer review the AGPL license to know exactly what its terms are. 

That said, our intention is not to restrict you from using cleanlab to clean up a dataset and train a better ML model or better analytics (with the model/analytics used however you see fit). We selected the AGPL license to ensure that folks who are building software platforms on top of cleanlab or including it in production code contribute equally to the community by open-sourcing their work as well.

For companies that would like to do the latter without open-sourcing their code, we do provide [commercial non-AGPL licenses](https://github.com/cleanlab/cleanlab?tab=readme-ov-file#commercial-licensing) that come with professional support from our ML experts.  Many big tech companies and startups have purchased such licenses with great outcomes, as have folks just wanting to improve datasets/models with professional support from our team.
