### ISSUE TITLE
Datalab is not available due to missing dependencies. 

### ISSUE THREAD

**Issue by YY-han** [cleanlab/cleanlab#1033]
# Stack trace

Traceback (most recent call last):
  File "...........", line 51, in <module>
    lab = Datalab()
  File "............/lib/python3.8/site-packages/cleanlab/__init__.py", line 29, in __call__
    raise ImportError(message)
ImportError: Datalab is not available due to missing dependencies. To install Datalab, run `pip install 'cleanlab[datalab]'`. (raised when trying to call with args: (), kwargs: {})

# Steps to reproduce

from cleanlab import Datalab
lab = Datalab()

# Additional information

cleanlab==2.6.0
datalab==1.1.4

pip install 'cleanlab[datalab]':
Requirement already satisfied: cleanlab[datalab] in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (2.6.0)
Requirement already satisfied: numpy>=1.22.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from cleanlab[datalab]) (1.24.4)
Requirement already satisfied: scikit-learn>=1.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from cleanlab[datalab]) (1.3.2)
Requirement already satisfied: tqdm>=4.53.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from cleanlab[datalab]) (4.66.2)
Requirement already satisfied: pandas>=1.4.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from cleanlab[datalab]) (2.0.3)
Requirement already satisfied: termcolor>=2.4.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from cleanlab[datalab]) (2.4.0)
Requirement already satisfied: datasets>=2.7.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from cleanlab[datalab]) (2.17.1)
Requirement already satisfied: filelock in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (3.13.1)
Requirement already satisfied: pyarrow>=12.0.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (15.0.0)
Requirement already satisfied: pyarrow-hotfix in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (0.3.8)
Requirement already satisfied: requests>=2.19.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (2.31.0)
Requirement already satisfied: xxhash in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (3.4.1)
Requirement already satisfied: multiprocess in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (0.70.16)
Requirement already satisfied: fsspec<=2023.10.0,>=2023.1.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from fsspec[http]<=2023.10.0,>=2023.1.0->datasets>=2.7.0->cleanlab[datalab]) (2023.10.0)
Requirement already satisfied: aiohttp in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (3.9.3)
Requirement already satisfied: huggingface-hub>=0.19.4 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (0.21.0)
Requirement already satisfied: packaging in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (23.2)
Requirement already satisfied: pyyaml>=5.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from datasets>=2.7.0->cleanlab[datalab]) (6.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from pandas>=1.4.0->cleanlab[datalab]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from pandas>=1.4.0->cleanlab[datalab]) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from pandas>=1.4.0->cleanlab[datalab]) (2024.1)
Requirement already satisfied: scipy>=1.5.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from scikit-learn>=1.1->cleanlab[datalab]) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from scikit-learn>=1.1->cleanlab[datalab]) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from scikit-learn>=1.1->cleanlab[datalab]) (3.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from aiohttp->datasets>=2.7.0->cleanlab[datalab]) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from aiohttp->datasets>=2.7.0->cleanlab[datalab]) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from aiohttp->datasets>=2.7.0->cleanlab[datalab]) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from aiohttp->datasets>=2.7.0->cleanlab[datalab]) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from aiohttp->datasets>=2.7.0->cleanlab[datalab]) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from aiohttp->datasets>=2.7.0->cleanlab[datalab]) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from huggingface-hub>=0.19.4->datasets>=2.7.0->cleanlab[datalab]) (4.10.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->cleanlab[datalab]) (1.10.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from requests>=2.19.0->datasets>=2.7.0->cleanlab[datalab]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from requests>=2.19.0->datasets>=2.7.0->cleanlab[datalab]) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from requests>=2.19.0->datasets>=2.7.0->cleanlab[datalab]) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/yang_clean/lib/python3.8/site-packages (from requests>=2.19.0->datasets>=2.7.0->cleanlab[datalab]) (2024.2.2)

I follow the prompts to run pip install 'cleanlab[datalab]' to install the dependencies and still get an error. I have tried various solutions but I really don't know what is going on and I would love to get your help. Thank you very much!

**Comment by YY-han** [comment]
Hello Elias,
Thank you very much for your generous and quick help. I tried these operations you said.


I first recreated the environment the way you described and replaced it with the new interpreter in pycharm. And I output the correct environment. But when we finally run the test, we still get an error:


D:\Anaconda3\envs\new_cleanlab_env\python.exe E:\papers\code\scr\test.py
Python executable: D:\Anaconda3\envs\new_cleanlab_env\python.exe
Traceback (most recent call last):
File "E:\papers\code\scr\test.py", line 6, in &amp;lt; module&amp;gt;
lab = Datalab({"X": [1, 2, 3, 4, 5], "y": ["a", "b", "a", "b", "a"]})
File "D:\Anaconda3\envs\new_cleanlab_env\lib\site-packages\cleanlab\__init__.py", line 29, in __call__
raise ImportError(message)
ImportError:&nbsp; Datalab is not available due to missing dependencies. To install Datalab,&nbsp; run `pip install 'cleanlab[datalab]'`. (raised when trying to call with args: ({'X': [1, 2, 3, 4, 5], 'y':&nbsp; ['a', 'b', 'a', 'b', 'a']},), kwargs: {})


Process has terminated, exit code 1



There were no problems with the environment configuration, but the final test still showed the original error. I'm not going to clear up exactly where this went wrong.




Thank you again for your generous answers. Best wishes.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elías ***@***.***&gt;; 
发送时间: 2024年2月28日(星期三) 晚上10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cleanlab/cleanlab] Datalab is not available due to missing dependencies.  (Issue #1033)





 
Hello @YY-han,
 
Thank you for bringing this to our attention! It looks like there might be a mix-up with the environment setup or package installation. It's a bit tricky to pinpoint without seeing the exact environment name from the stack trace you've shared.
 
Regarding the datalab==1.1.4 package, it's curious because it seems to reference an unrelated package. Could there have been a typo, or was there a specific reason for choosing this version?
 
To tackle the issue head-on, creating a fresh environment might be our best bet. It sounds like you're familiar with conda, so let's use that to our advantage:
 
Quick Setup for a Fresh Start
  
 
Create a New Environment:
 conda create -n new_cleanlab_env python=3.8 -y
 
 
 
Activate Your New Environment:
 conda activate new_cleanlab_env
 
 
 
Install cleanlab with Extras:
 pip install cleanlab[datalab]
 
  
Running Python
  
For console sessions, ensure you're in new_cleanlab_env. Running which pip and which python should
 
For Jupyter or VSCode, ensure the environment's kernel or interpreter is correctly set.
  
Double-Check Your Environment
 import sys print(f"Python executable: {sys.executable}")
 
This step is crucial to verify you're working in the right environment.
 
Give It a Try
 from cleanlab import Datalab lab = Datalab({"X": [1, 2, 3, 4, 5], "y": ["a", "b", "a", "b", "a"]}) print(lab)
 
You should expect to see:
 Datalab(task=Classification, checks_run=False, num_examples=5, issues_identified=Not checked)
 
Let me know how it goes or if there's anything else you're curious about. We'll make sure to get this sorted out together.

**Comment by YY-han** [comment]
> Hello @YY-han,
> 
> Thank you for bringing this to our attention! It looks like there might be a mix-up with the environment setup or package installation. It's a bit tricky to pinpoint without seeing the exact environment name from the stack trace you've shared.
> 
> Regarding the `datalab==1.1.4` package, it's curious because it seems to reference an [unrelated package](https://pypi.org/project/datalab/). Could there have been a typo, or was there a specific reason for choosing this version?
> 
> To tackle the issue head-on, creating a fresh environment might be our best bet. It sounds like you're familiar with `conda`, so let's use that to our advantage:
> 
> ### Quick Setup for a Fresh Start
> 1. **Create a New Environment:**
>    ```shell
>    conda create -n new_cleanlab_env python=3.8 -y
>    ```
> 2. **Activate Your New Environment:**
>    ```shell
>    conda activate new_cleanlab_env
>    ```
> 3. **Install `cleanlab` with Extras:**
>    ```shell
>    pip install cleanlab[datalab]
>    ```
> 
> ### Running Python
> * For console sessions, ensure you're in `new_cleanlab_env`. Running `which pip` and `which python` should
> * For Jupyter or VSCode, ensure the environment's kernel or interpreter is correctly set.
> 
> ### Double-Check Your Environment
> ```python
> import sys
> print(f"Python executable: {sys.executable}")
> ```
> 
> This step is crucial to verify you're working in the right environment.
> 
> ### Give It a Try
> ```python
> from cleanlab import Datalab
> 
> lab = Datalab({"X": [1, 2, 3, 4, 5], "y": ["a", "b", "a", "b", "a"]})
> 
> print(lab)
> ```
> 
> You should expect to see:
> 
> ```python
> Datalab(task=Classification, checks_run=False, num_examples=5, issues_identified=Not checked)
> ```
> 
> Let me know how it goes or if there's anything else you're curious about. We'll make sure to get this sorted out together.

Thank you very much for your generous and quick help, [elisno](https://github.com/elisno). I tried these operations you said.

I first recreated the environment the way you described and replaced it with the new interpreter in pycharm. And I output the correct environment. But when we finally run the test, we still get an error:

D:\Anaconda3\envs\new_cleanlab_env\python.exe E:\papers\code\scr\test.py
Python executable: D:\Anaconda3\envs\new_cleanlab_env\python.exe
Traceback (most recent call last):
File "E:\papers\code\scr\test.py", line 6, in &lt; module&gt;
lab = Datalab({"X": [1, 2, 3, 4, 5], "y": ["a", "b", "a", "b", "a"]})
File "D:\Anaconda3\envs\new_cleanlab_env\lib\site-packages\cleanlab\__init__.py", line 29, in __call__
raise ImportError(message)
ImportError:  Datalab is not available due to missing dependencies. To install Datalab,  run `pip install 'cleanlab[datalab]'`. (raised when trying to call with args: ({'X': [1, 2, 3, 4, 5], 'y':  ['a', 'b', 'a', 'b', 'a']},), kwargs: {})

Process has terminated, exit code 1

I think there were no problems with the environment configuration, but the final test still showed the original error. I'm not going to clear up exactly where this went wrong. TAT

Thank you again for your generous answers. Best wishes.

**Comment by yzf072** [comment]
Hello~ How did you solve it? I had the same problem
