### ISSUE TITLE
get rid of warnings in the datalab quickstart tutorial

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#1053]
This tutorial has some minor warnings:  https://docs.cleanlab.ai/master/tutorials/datalab/datalab_quickstart.html

Should be easy to get rid of by modifying the dataset appropriately, just make sure the results are still interpretable as for the current dataset

**Comment by jwmueller** [comment]
remaining warning:

`/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sklearn/neighbors/_base.py:246: EfficiencyWarning: Precomputed sparse input was not sorted by row values. Use the function sklearn.neighbors.sort_graph_by_row_values to sort the input by row values, with warn_when_not_sorted=False to remove this warning.
`

**Comment by elisno** [comment]
> remaining warning:
>
> /opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/sklearn/neighbors/_base.py:246: EfficiencyWarning: Precomputed sparse input ...

I'm unable to reproduce this warning locally and on Colab.

![image](https://github.com/cleanlab/cleanlab/assets/18127060/ba3b0a3d-cd5e-448e-8c48-c0e2f70ae766)
