### ISSUE TITLE
Difference of object detection confident learning with objectlab paper 

### ISSUE THREAD

**Issue by crazyboy9103** [cleanlab/cleanlab#1059]
I'm currently using cleanlab to study confident learning and its implementations, and i found that the implementation for object detection is slightly different from what [objectlab paper](https://arxiv.org/pdf/2309.00832.pdf), when it calculates the similarity between boxes. In section 2.1, objectlab paper states that "sim(B1, B2) = α · k(B1, B2) + (1 − α) · IoU(B1, B2) ... k(·, ·) is a Gaussian kernel similarity between 4D vectors defined by the outer edges of each box =exp(−||⃗b1 −⃗b2||/σ) where the entries of ⃗b1 (or ⃗b2) are the coordinates of the top-left and bottom-right corners of B1 (or B2) **normalized to unit interval.**", but it seems that the boxes are not normalized to unit interval when calculating the gaussian distance. Also, instead of 4D vector, the code uses the center points to calculate the distance. Could someone explain why coordinates were not normalized as suggested, and the center point was used?

```python
# https://github.com/cleanlab/cleanlab/blob/master/cleanlab/object_detection/rank.py#L403
def _euc_dis(box1: List[float], box2: List[float]) -> float:
    """Calculates the Euclidean distance between `box1` and `box2`."""
    x1, y1 = (box1[0] + box1[2]) / 2, (box1[1] + box1[3]) / 2
    x2, y2 = (box2[0] + box2[2]) / 2, (box2[1] + box2[3]) / 2
    p1 = np.array([x1, y1])
    p2 = np.array([x2, y2])
    val2 = np.exp(-np.linalg.norm(p1 - p2) * EUC_FACTOR)
    return val2


def _get_dist_matrix(bb1_list: np.ndarray, bb2_list: np.ndarray) -> np.ndarray:
    """Returns a distance matrix of distances from all of boxes in bb1_list to all of boxes in bb2_list."""
    wd = np.zeros(shape=(len(bb1_list), len(bb2_list)))
    for i in range(len(bb1_list)):
        for j in range(len(bb2_list)):
            wd[i][j] = _euc_dis(bb1_list[i], bb2_list[j])
    return wd
```

**Comment by jwmueller** [comment]
Thanks for point this out. I believe it was just a wording mistake in the paper that we'll get fixed when we can
