### ISSUE TITLE
Object detection, segmentation k-fold practical issue

### ISSUE THREAD

**Issue by crazyboy9103** [cleanlab/cleanlab#1068]
For classification, I've utilized k-fold methods that consider class distributions, such as StratifiedKFold, for better prediction in each fold. However, for detection and segmentation, it is not so straightforward. 

For object detection, I thought StratifiedGroupKFold might be a possible candidate, as it ensures that the train/test splits for each fold contain non-overlapping images while also accounting for class distribution. However, I'm unsure how to implement k-fold cross-validation of similar kind in segmentation.

Could anyone share their insights or experiences on how to apply k-fold cross-validation for detection/segmentation? Any advice, tips, or resources would be incredibly appreciated.

**Comment by jwmueller** [comment]
We typically just do random K-fold splits for object detection and segmentation.
An example is here: https://github.com/cleanlab/examples/blob/master/object_detection/detectron2_training-kfold.ipynb

But you might get better results via a fancier data splitting scheme that better preserves class distributions over the folds.
