### ISSUE TITLE
In the “Synthetic Data Quality” part， do we need the same amount of real data and generated data

### ISSUE THREAD

**Issue by Lucy-IM** [cleanlab/cleanlab#1093]

**Comment by jwmueller** [comment]
Hi @Lucy-IM, I presume you're referring to this Cleanlab Studio tutorial?
https://help.cleanlab.ai/tutorials/synthetic_data/

or the associated blogposts?
https://cleanlab.ai/blog/synthetic-image-with-stable-diffusion/
https://cleanlab.ai/blog/studio-synthetic-data/

Regardless, the answer is No. You don't have to have the same amount of real data vs generated data. Most of our customers have much more synthetic data than real data.
