### ISSUE TITLE
Pass kwargs to base estimator fit function

### ISSUE THREAD

**Issue by davidfstein** [cleanlab/cleanlab#110]
I want to pass an eval set to my LGBMClassifier instance in order to take advantage of early stopping. The eval set is passed to the lgbm model fit function. Is it possible to pass arguments to the fit function of the base estimator when it is wrapped by the LearningWithNoisyLabels model?

**Comment by jwmueller** [comment]
This will be possible in the next release of cleanlab, stay tuned!
