### ISSUE TITLE
image datalab tutorial broken:  Getting build error RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 1, 1, 28, 28]

### ISSUE THREAD

**Issue by mturk24** [cleanlab/cleanlab#1103]
For this simple [PR](https://github.com/cleanlab/cleanlab/pull/1102) wanted to report this Github pages build error

`RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 1, 1, 28, 28]`

showing up in the [build logs](https://github.com/cleanlab/cleanlab/actions/runs/8757918162/job/24037594774?pr=1102)

**Comment by jwmueller** [comment]
Thanks for reporting!  Please also name the asset that is broken when you report for easier triage (see how I edited the name). 

This is perhaps due to a backwards-incompatible upgrade in a package version dependency of this tutorial

**Comment by elisno** [comment]
This issue has been successfully resolved with #1108 

In the latest update of the `datasets` library, there has been a notable change regarding how image data is handled when using `Dataset.with_format("torch")`. Specifically, for image columns initially stored as PIL objects, the pixel values are now consistently formatted in the [channel, height, width] structure. This update streamlines the process for handling grayscale images, which were previously represented in a [height, width] format. Consequently, users are no longer required to manually add a channel dimension for such images, as demonstrated in the image handling tutorial.
