### ISSUE TITLE
3D Cleanlab / DCAI ?

### ISSUE THREAD

**Issue by friedang** [cleanlab/cleanlab#1109]
Hi there,

Thank you so much for your great work and DCAI course! 

Will there be cleanlab for 3D data (e.g. KITTI) any time soon or is there already a package or any other type of work in that domain that you could recommend? :)

Best wishes

Friedrich

**Comment by jwmueller** [comment]
Thank you for the kind words! 
We do not currently have plans to extend this package to 3D object detection.
  
If you're working at a company, we do offer enterprise software to get label quality assurance for 3D object detection, which we've pioneered with multiple large autonomous vehicle firms.  Learn more by requesting a meeting:  https://cleanlab.ai/sales/
