### ISSUE TITLE
CI fails due to an unnannounced fastText release

### ISSUE THREAD

**Issue by elisno** [cleanlab/cleanlab#1143]
A test case in `tests/test_frameworks.py` fails due to a recent [fastText release](https://pypi.org/project/fasttext/), which has yet to be announced. No information can be found in the [repository](https://github.com/facebookresearch/fastText), as it was archived in Mar 19, 2024.

_Originally posted by @elisno in https://github.com/cleanlab/cleanlab/issues/1142#issuecomment-2163993850_

**Comment by elisno** [comment]
I'm unable to reproduce the failing test locally, after updating to fastText 0.9.3.

**Comment by jwmueller** [comment]
just version cap it?  All of these uncommon package integrations in test_frameworks can be version capped in CI I think
