### ISSUE TITLE
dead link in clean lab landing page

### ISSUE THREAD

**Issue by delkind-dnsf** [cleanlab/cleanlab#1147]
The quickstart page for cleanlab has a dead link.

> [CleanLearning](https://docs.cleanlab.ai/stable/cleanlab/classification.html#cleanlab.classification.CleanLearning) also works with models from most standard ML frameworks by wrapping the model for scikit-learn compliance, e.g. [tensorflow/keras](https://docs.cleanlab.ai/stable/tutorials/text.ipynb) (using our KerasWrapperModel), [pytorch](https://docs.cleanlab.ai/stable/tutorials/image.ipynb) (using skorch package), etc.

- The pytorch link is dead. https://docs.cleanlab.ai/stable/tutorials/image.ipynb
- The tensorflow/keras link is dead. https://docs.cleanlab.ai/stable/tutorials/text.ipynb

**Comment by jwmueller** [comment]
thanks for reporting! fixed in https://github.com/cleanlab/cleanlab/pull/1148
