### ISSUE TITLE
multi_annotator labels

### ISSUE THREAD

**Issue by tcsmaster** [cleanlab/cleanlab#1156]
I am trying to use the template showed in the "Active Learning with Multiple Data Annotators via ActiveLab" example (https://github.com/cleanlab/examples/blob/master/active_learning_multiannotator/active_learning.ipynb).

I have a labeled dataset, and also an unlabeled dataset. I am trying to create the `multiannotator_labels` array with let's say 20 columns for annotators but I get the error: `labels_multiannotator cannot have columns with all NaN, each annotator must annotator at least one example`. 

Do I have to artificially put the label for each data into one of the 20 columns making sure that every column gets at least one label?

**Comment by jwmueller** [comment]
`multiannotator_labels` should only correspond to `X_labeled`, the data labeled so far.
Each column of `multiannotator_labels` corresponds to one annotator, if you have a column that is entirely empty (this annotator didn't label anything yet), then just omit that column entirely.

**Comment by tcsmaster** [comment]
Ok, I understand that. I also made some progress regarding this on my own (btw really appreciate the verbose error statements, they help a lot!) But if the labels were not generated from these anontators, but from outside source, what should my labels_multiannotator be? should it even exists?

**Comment by jwmueller** [comment]
> Ok, I understand that. I also made some progress regarding this on my own (btw really appreciate the verbose error statements, they help a lot!) But if the labels were not generated from these annotators, but from outside source, what should my labels_multiannotator be? should it even exists?

Could you describe more what you're trying to achieve?  If you have one outside source of labels and many annotators, you could just treat the outside source as a single annotator.  

If instead you only have one label per example, even if multiple annotators were involved, Cleanlab won't be able to learn much about the annotators' relative strengths/weaknesses.  In that case you can follow this tutorial:
https://github.com/cleanlab/examples/blob/master/active_learning_single_annotator/active_learning_single_annotator.ipynb

**Comment by tcsmaster** [comment]
Absolutely, should have started with that.
I am working on the localization of the [Nace Rev 2.1](https://ec.europa.eu/eurostat/web/products-eurostat-news/w/wdn-20230210-1) automatic recoding of economic entitites. The main problem is that some codes are splitting into many brand new codes, and we'd like to automate the recoding of these enterprises. Each enterprise only gets one code (the main economic activity).
Our institute conducted a survey for a sample of these enterprises, for those I have ground truth new labels, now I need to try to relabel the enterprises outside of this sample.
So, according to your guidance, this ground truth data should be the single annotator?

**Comment by jwmueller** [comment]
> Absolutely, should have started with that. I am working on the localization of the [Nace Rev 2.1](https://ec.europa.eu/eurostat/web/products-eurostat-news/w/wdn-20230210-1) automatic recoding of economic entitites. The main problem is that some codes are splitting into many brand new codes, and we'd like to automate the recoding of these enterprises. Each enterprise only gets one code (the main economic activity). Our institute conducted a survey for a sample of these enterprises, for those I have ground truth new labels, now I need to try to relabel the enterprises outside of this sample. So, according to your guidance, this ground truth data should be the single annotator?

Yes that'd be my recommendation to try first. If you have enough of the ground truth data, also consider training your ML model solely on the ground truth data only, so its predictions will be more trustworthy.

**Comment by tcsmaster** [comment]
Ok, will try that! Thank you for the help!
