### ISSUE TITLE
links in the misc datalab workflows tutorial don't work

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#1165]
example links that are broken:

https://docs.cleanlab.ai/stable/tutorials/datalab/issue_type_description.html#data-valuation-issue

https://docs.cleanlab.ai/stable/tutorials/datalab/issue_type_description.html#underperforming-group-issue

**Comment by jwmueller** [comment]
For this reason, also generally not a good idea to write [here](link) instead of [Issue Types Guide](link)

because the latter is more easy to work with in case the link got broken

**Comment by elisno** [comment]
Resolved in #1168
