### ISSUE TITLE
Please don't spam Github users via email

### ISSUE THREAD

**Issue by MohamedElashri** [cleanlab/cleanlab#1169]
## The problem

On Jun 28th, I received email from cleanlab about some celebration. It arrived on an email that I control its domain and I use it on github profile and commits only. 

I stared the project in the past ( don't remember when) but it seems you are scraping emails of users who started the project (maybe more) which is annoying and not nice. It is also against Github ToS. 

In the email header it seems that this is an email campaign and not targeted based on usage of HubSpot. 

## Expected behavior

Please do not spam other GitHub users via email

**Comment by jwmueller** [comment]
We're sorry for bothering you, thanks for the heads up. Will make sure it doesn't happen again
