### ISSUE TITLE
Can I use CleanLab for a regression task dataset with numerous (>40) numerical and categorical variables?

### ISSUE THREAD

**Issue by AndreaPi** [cleanlab/cleanlab#1203]
Hi,

I would like to use CleanLab to analyze a tabular dataset I have with ~6000 rows and ~40 columns. The columns are mostly numerical, but some of them are low-cardinality categorical. I dummy-encode the categorical variables, which increases the number of input features to between 50 and 60. The task is a regression one, i.e., I have a single target column which is a float. Can I use CleanLab to identify possibly noisy samples? I'm using mostly tree-based models such as xgboost and RandomForests (which work surprisingly well for my issue, probably because there's *a lot* of noise in the data).

**Comment by jwmueller** [comment]
Yes you should be able to follow:  https://docs.cleanlab.ai/stable/tutorials/regression.html

Especially the final section:  https://docs.cleanlab.ai/stable/tutorials/regression.html#5.-Other-ways-to-find-noisy-labels-in-regression-datasets
