### ISSUE TITLE
Query regarding eq.1 in the paper.

### ISSUE THREAD

**Issue by as3895** [cleanlab/cleanlab#133]
W.r.t the paper: https://arxiv.org/pdf/1911.00068.pdf
What happens if none of the predicted prob for a sample **x** is above threshold(_t_) for any of the classes?
Which bin do you assign the sample to in this case?

**Comment by datahub-projects** [comment]
Please excuse me for commandeering this thread -- I am working on a project called Cloudburst and I saw in the logs that user @as3895 attempted to sign up, but received a timeout error. We have fixed the bug that caused the timeout, so please try again if you are still interested in Cloudburst. You can also contact us at support@cloudburst.host.

**Comment by cgnorthcutt** [comment]
Hi @as3895 - great question! You are correct: the example would **not be counted** when estimating the joint distribution of true and noisy labels. So, for a dataset with cows, pigs, and dogs... an image of an empty grass field would not get counted in the joint estimate. This is the proper behavior for the joint which estimates the class-conditional probability of label errors (not the probability of out-of-distribution data), but may resulting in underestimating the total number of errors. This will be addressed in a future `cleanlab` release later this year -- we are adding support for automatically detecting out-of-distribution examples directly in `cleanlab`.
