### ISSUE TITLE
Remove sklearn.utils dependencies

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#139]
[sklearn.utils](https://scikit-learn.org/stable/developers/utilities.html#developers-utils) are meant to be used internally within the scikit-learn package. They are not guaranteed to be stable between versions of scikit-learn. So depending on this submodule may limit cleanlab compatibility across sklearn versions.

Would not be too much work to replace the few cleanlab functions currently being imported from sklearn.utils.

**Comment by ayush-kumar-1** [comment]
Hi, I'd love to help contribute to cleanlab by working on this issue. Any pointers for starting to profile which functions need to be written and how to integrate them where they're needed?

**Comment by jwmueller** [comment]
Awesome to hear @ayush-kumar-1 
I actually think this issue has already been resolved by: https://github.com/cleanlab/cleanlab/pull/301/

Do you still see sklearn.utils being used anywhere in the package?

**Comment by jwmueller** [comment]
If this is resolved, you could help us work on this issue:  https://github.com/cleanlab/cleanlab/issues/307
just focusing on adding static typing for a single file for now, say one in the internal/ or experimental/ folders.

**Comment by jwmueller** [comment]
Alternatively something that is extremely helpful for us is if you can help improve our unit tests:

Improve efficiency: Many of the existing unit tests (in cleanlab/tests/) can be made more efficient without fundamentally changing the quality of the test. We recommend timing the unit tests to identify which ones take the longest and focusing on those. Usually these will be tests that rely on some toy dataset. One way to speed such tests up is to reduce the size of the dataset, but be careful that the test remains useful and still checks for the key properties it is assessing!

Improve quality of checks: Some of the existing unit tests only verify certain code runs properly. These tests can be improved to verify the outputs from the code match the expected outputs (both in terms of object characteristics like array shape or Python type, as well as the values themselves).

Add more unit tests to improve code coverage:  You can check codecov runs for the lastest master branch and find lines of code that aren't currently covered by any unit test. It would be very helpful if you can add a unit test to cover such lines of code.

Important: any new unit tests you add must run very quickly! Ideally in under 1sec. If your tests run on some data, try to use the smallest dataset possible for the test to still be useful.

Feel free to message me (Jonas Mueller) in our Slack if you'd like to discuss ideas more interactively!  https://cleanlab.ai/slack

**Comment by cgnorthcutt** [comment]
Other easy places to get started:
* easiest -- submit a PR to fix typos
* improve issues in docstrings 
* add static typing and return types
* improve code reusability and reduce redundancy, for example by adding to internal/util.py if you see some auxiliary code that is used frequently throughout the package and could be modularized as a simple helper utility.

**Comment by ayush-kumar-1** [comment]
> Awesome to hear @ayush-kumar-1 I actually think this issue has already been resolved by: #301
> 
> Do you still see sklearn.utils being used anywhere in the package?

Some quick greps showed me that `sklearn.utils` is not mentioned anywhere in the codebase.

**Comment by jwmueller** [comment]
Thanks for also checking, I'll close this issue and we can continue discussing in Slack
