### ISSUE TITLE
Add CI to ensure that Jupyter notebooks don't include output

### ISSUE THREAD

**Issue by anishathalye** [cleanlab/cleanlab#168]
Preserving the output cells in Jupyter notebooks that are checked in to this repo bloat the repo size, and keeping the output is not necessary because the notebooks are run as part of the CI for producing docs.

For example, in #165, the `audio.ipynb` is 112K (and now part of the repo history forever), while clearing the output cells reduces that size down to 24K. I suspect that Git's delta compression will also work better without the output cells there as we make changes to the notebook. Also, the diffs will be more readable.

We should add CI that enforces that Jupyter notebooks checked in to the repo don't have any output cells. In the meantime, let's be careful and do this manually. CC @weijinglok @JohnsonKuan @jwmueller

**Comment by jwmueller** [comment]
@weijinglok had a git pre-commit hook that is supposed to do this, @weijinglok can you check in with Anish why your pre-commit hook is not working?
