### ISSUE TITLE
CI: Run tests with oldest versions of supported dependencies

### ISSUE THREAD

**Issue by anishathalye** [cleanlab/cleanlab#191]
Our `setup.py` specifies the minimum versions of dependencies that we require, but we do not test that these versions are adequate for running cleanlab. Our CI setup just does a `pip install`, which installs the _latest_ available versions of dependencies.

This came up when we were thinking about which minimum version of Pandas to require.

Some initial thoughts about this:

pip does not support this out of the box. There is an open issue (https://github.com/pypa/pip/issues/8085), but it has been open since April 2020, so it's unclear if the functionality will be implemented any time soon.

Jupyter implemented their own workaround: https://github.com/jupyterlab/maintainer-tools/pull/51. From a quick skim, it looks like it effectively installs the minimum versions of all packages specified with `>` style constraints.

I haven't thought deeply about it, but this seems potentially problematic, if e.g. cleanlab depends on `A > 1.2, B > 2.6`, but A 1.2 depends on `B > 2.7`, then having cleanlab depend on `A == 1.2, B == 2.6` would result in unsatisfiable constraints. In such situations, it's unclear what is even the right thing to do. Without additional assumptions on dependencies' dependencies, there isn't a clear "minimum versions of all packages".

Perhaps we could, for _each_ dependency, test that we can work with its minimum version? So for the above, we'd test with just the additional constraint `A == 1.2` (and no constraints on any other deps), and then just the additional constraint `B == 2.6`.

**Comment by jwmueller** [comment]
Addressed by: https://github.com/cleanlab/cleanlab/pull/701
