### ISSUE TITLE
License file not included in source distribution.

### ISSUE THREAD

**Issue by ndmaxar** [cleanlab/cleanlab#24]

**Comment by cgnorthcutt** [comment]
@ndmaxar Thanks Can you clarify, perhaps with a suggestion to change setup.py?

**Comment by cgnorthcutt** [comment]
@ndmaxar bump

**Comment by ndmaxar** [comment]
Adding this to the kwargs of setup should do the trick.
```py
package_data={
    "": ["LICENSE"]
}
```

**Comment by cgnorthcutt** [comment]
Hi @ndmaxar , I've added the LICENSE as package data. Also included it in the MANFEST.in. And also added it in license_files in the setup() of setup.py. It looks like in all cases (on my machines), the LICENSE file is included, but not in the same file as source, instead its included in the distribution-info folder. For example, on my machine, using miniconda as a package manager:

```
/Users/cgn/miniconda3/envs/py37_test/lib/python3.7/site-packages/cleanlab-1.0.dist-info  # Contains the LICENSE
/Users/cgn/miniconda3/envs/py37_test/lib/python3.7/site-packages/cleanlab  # Contains the code, not the LICENSE
```

Can you confirm? Thanks!

**Comment by BastianZim** [comment]
Hi @cgnorthcutt I'm not the original author but I can confirm that it is included, thanks!

**Comment by cgnorthcutt** [comment]
Thank you for confirming @BastianZim . Will close :)
