### ISSUE TITLE
cleanlab.latent_estimation.estimate_confident_joint_and_cv_pred_proba gives ValueError

### ISSUE THREAD

**Issue by fahadjahangir** [cleanlab/cleanlab#244]
I have trained a TempCNN model and the training data has a shape:
 X_train: (14235, 72, 12)  y_train: (14235,)

While using the method: 
> cleanlab.latent_estimation.estimate_confident_joint_and_cv_pred_proba(X_train, y_train, clf=model,) 

I am getting a following error:

> ValueError: Found array with dim 3. Estimator expected <= 2.

![grafik](https://user-images.githubusercontent.com/15300417/165256253-16f31520-6c0a-4ccd-b89e-1453a0886c7f.png)

Does that mean the X_train has to be 2D? how can I make it work if X_train is 3D?

**Comment by anishathalye** [comment]
I believe this is fixed in Cleanlab 2.0. Could you try upgrading to that and using this function: https://docs.cleanlab.ai/v2.0.0/cleanlab/count.html#cleanlab.count.estimate_confident_joint_and_cv_pred_proba

**Comment by fahadjahangir** [comment]
Thank you, indeed the older version of Cleanlab was the issue.
