### ISSUE TITLE
multi-label broadcasting issue: ValueError: operands could not be broadcast together with shapes (51,XXX) (30,)

### ISSUE THREAD

**Issue by suneeta-mall** [cleanlab/cleanlab#266]
Based on the discussion here https://github.com/cleanlab/cleanlab/pull/264/files#r878641672 I get the feeling that this may be a known issue.  
For records, I have used version '2.0.0' of cleanlab.

When I run the filter method as shown following: 
```
In [23]: ordered_label_errors = find_label_issues(
    ...:     truths,
    ...:     cpreds,
    ...:     return_indices_ranked_by="normalized_margin",
    ...:     multi_label=True,
    ...: )
```

and I don't have truth for all known classes then the API fails to calculate the threshold, with the following broadcast error:

```
File ~/.local/lib/python3.8/site-packages/cleanlab/count.py:272, in _compute_confident_joint_multi_label(labels, pred_probs, thresholds, calibrate, return_indices_of_off_diagonals)
    270     thresholds = [np.mean(pred_probs[:, k][k_in_l[k]]) for k in range(K)]
    271 # Create mask for every example if for each class, prob >= threshold
--> 272 pred_probs_bool = pred_probs >= thresholds
    274 # Compute confident joint
    275 # (no need to avoid collisions for multi-label, double counting is okay!)
    276 confident_joint = np.array([pred_probs_bool[k_in_l[k]].sum(axis=0) for k in range(K)])

ValueError: operands could not be broadcast together with shapes (51,XXX) (30,)
```

**Comment by cgnorthcutt** [comment]
Hi @suneeta-mall ! https://github.com/cleanlab/cleanlab/pull/264 has been merged!

Could you let us know if you're having any more issues?

**Comment by aditya1503** [comment]
Hi @suneeta-mall 
In cleanlab v2.2, we did a major overhaul of the functionality for multi-label classification. All of these issues should now be resolved, and cleanlab's new label error detection capabilities for multi-label classification are much more powerful and easy to use!

Get started here: https://docs.cleanlab.ai/stable/tutorials/multilabel_classification.html

You can refer to the expected labels format when multi_label is True here: https://github.com/cleanlab/cleanlab/blob/75bac0a28438fc606c7caff52d518774b33a5101/cleanlab/filter.py#L63


And definitely please open a new issue (stating which cleanlab version you are using) if you still encounter any problems using cleanlab for multi-label datasets.

**Comment by suneeta-mall** [comment]
Good stuff @aditya1503 🚀 ! I will check it out in the coming days!
