### ISSUE TITLE
from cleanlab.pruning import get_noise_indices

### ISSUE THREAD

**Issue by lili1234567890** [cleanlab/cleanlab#275]
ModuleNotFoundError: No module named 'cleanlab.pruning'

**Comment by cgnorthcutt** [comment]
Use `cleanlab.filter.find_label_issues()` instead. This was updated in v2.0.

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！
