### ISSUE TITLE
What is the change in parameters between get_noise_indices( ) and  cleanlab.filter.find_label_issues( ) ?

### ISSUE THREAD

**Issue by lili1234567890** [cleanlab/cleanlab#276]
What is the change in parameters between get_noise_indices( ) and  cleanlab.filter.find_label_issues( ) ?
I'm just going to change the function and still get an error
TypeError: find_label_issues() got an unexpected keyword argument 's'
thanks 

> Use `cleanlab.filter.find_label_issues()` instead. This was updated in v2.0.

**Comment by calebchiam** [comment]
Hi @lili1234567890, please refer to the migration guide here: https://docs.cleanlab.ai/v2.0.0/migrating/migrate_v2.html

**Comment by cgnorthcutt** [comment]
Hi @lili1234567890 , @calebchiam's suggestion should help you make the transition from cleanlab v1.0 to v2.0.0.  (e.g., the named parameter `s` was replaced by `labels`)

If you want to see what the new parameter definitions are for `cleanlab.filter.find_label_issues()`, go to https://github.com/cleanlab/cleanlab/blob/07c8ce655d954ae66222c51659816d899c541a8d/cleanlab/filter.py#L269

**Comment by lili1234567890** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，邮件我已收到，祝好！
