### ISSUE TITLE
Stable version of docs warns that it is out of date

### ISSUE THREAD

**Issue by calebchiam** [cleanlab/cleanlab#300]
Visit https://docs.cleanlab.ai/stable/cleanlab/rank.html for example.

<img width="892" alt="image" src="https://user-images.githubusercontent.com/14286996/176327959-bd16389b-49e0-4fec-9c82-796e1b9e3b47.png">

Latest stable version linked in 'here' points to: https://docs.cleanlab.ai/v2.0.0/index.html -- not sure if this is intended?

# Additional information

Issue is present across browsers.

**Comment by jwmueller** [comment]
Thanks for pointing out, I believe this should automatically addressed when we tag and release the next version as this version of the stable/ was manually linked to the existing v2.0.0, but stable/ will be auto-linked to future released versions 
(hence why docs.cleanlab.ai currently does not redirect to it).

Still good reminder for me to verify this is actually true at the next release :)

**Comment by jwmueller** [comment]
Reminder:  upon next release, also update all external links to point to stable instead.
