### ISSUE TITLE
AttributeError: 'NeuralNetClassifier' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by APeiZou** [cleanlab/cleanlab#302]
AttributeError: 'NeuralNetClassifier' object has no attribute 'cuda'

**Comment by cgnorthcutt** [comment]
This issue is likely unrelated to cleanlab and likely has to do with your hardware and software installation for whichever package your `NeuralNetClassifier` object belongs to. I can't debug further until you share the context, calling code, and inputs.
