### ISSUE TITLE
Multi-label classifiers and recommendation for prune method

### ISSUE THREAD

**Issue by avostryakov** [cleanlab/cleanlab#31]
Thanks for cleanlab!

Do you have examples of multi-label classification tasks? I'm curious what prune method to use in this case: prune by noise rate, prune by class, or both?

**Comment by sylvainma** [comment]
I am also looking for an example when the target `y` is a multi-output one:
```
[[0 1 0 0 1], [1 0 0 0 1], ...]
```

Any trick?

**Comment by jwmueller** [comment]
In case there is any chance this information is still useful to you:

In cleanlab v2.2, we did a major overhaul of the functionality for multi-label classification. cleanlab's new label error detection capabilities for multi-label classification are much more powerful and easy to use!

Get started here:  https://docs.cleanlab.ai/stable/tutorials/multilabel_classification.html

This tutorial demonstrates how to handle multi-output targets in the format you have.

We also published a paper detailing the new algorithms cleanlab v2.2 uses to estimate label errors in multi-label datasets:
[Identifying Incorrect Annotations in Multi-Label Classification Data](https://arxiv.org/abs/2211.13895)

Through extensive benchmarking, this paper answers questions about which label error detection algorithms to use for multi-label data (that are the cleanlab default settings post v2.2). 

And definitely please open a new issue (stating which cleanlab version you are using) if you still encounter any problems using cleanlab for multi-label datasets!
