### ISSUE TITLE
May I set the sample_weight parameter manually？

### ISSUE THREAD

**Issue by liumengna123** [cleanlab/cleanlab#33]
Hi, It's a pretty lib. When I try to train model with cleanlab, I find it is not allowed to set sample_weight manually. It is inteligent to set sample weight according to the ratio of positive samples and negitave samples. However, I need to tun the paramater for better performance. 
Thank you for your contribution about this lib.

**Comment by cgnorthcutt** [comment]
Sure thing. Are you familiar with how to submit a pull request? Please submit a pull request and I'll check it. Please add testing for the pull request.

**Comment by cgnorthcutt** [comment]
@liumengna123 bump.

**Comment by jwmueller** [comment]
This has been addressed in: https://github.com/cleanlab/cleanlab/pull/248
So you can now pass in custom datapoint weights via `sample_weight` argument of `CleanLearning.fit()` if you install the master branch version of cleanlab.

Feel free to re-open this issue if you still have questions!
