### ISSUE TITLE
Length of labels in Quick start codeblock 

### ISSUE THREAD

**Issue by coralexbadeaYonder** [cleanlab/cleanlab#330]
![image](https://user-images.githubusercontent.com/107546276/182579719-d4bde4e2-31ae-4220-8a15-fd288978748e.png)
The code is from step 2 https://docs.cleanlab.ai/v2.0.0/index.html#find-label-errors-in-your-data
```
from cleanlab.filter import find_label_issues

ordered_label_issues = find_label_issues(
    labels=labels,
    pred_probs=pred_probs,
    return_indices_ranked_by='self_confidence',
)
```

Why is there an assertion of  **assert len(labels) == len(pred_probs)** when it is stated in docstring that pred_probs should have shape (N, K) and labels length K? 
Thanks ;)

**Comment by jwmueller** [comment]
Hi, I've just merged a PR to address this confusion, hopefully that will clarify things a bit!

https://github.com/cleanlab/cleanlab/pull/331

**Comment by jwmueller** [comment]
Labels should have length `N`, where `N` = the number of examples in your dataset. Each example should have one label, which is an integer in {0,1,...,K-1} for a dataset with `K` classes.

`pred_probs` is the prediction for each example in the dataset, which is why we should have: `len(pred_probs) == len(labels) == N` for a dataset containing `N` examples.

**Comment by coralexbadeaYonder** [comment]
Awesome that makes sense. So just to make sure does this look like valid input? 
![image](https://user-images.githubusercontent.com/107546276/182590055-417b23f7-9299-4477-a919-187697f487ad.png)

Because I still got a different error.
![image](https://user-images.githubusercontent.com/107546276/182590199-eb52fdc2-214e-45bd-9861-94f06f7f710f.png)

**Comment by coralexbadeaYonder** [comment]
Ok so the problem was that the labels should contain all the available classes and each class should appear more than one time. Cool. Thank you for help, I will continue exploring how the library works.

**Comment by jwmueller** [comment]
@coralexbadeaYonder Glad to hear it's working for you now!

Could you by any chance share the labels, pred_probs you used to get that error above?  That is not an error message we should be giving users, so hopefully we can debug it and give a clearer error message.  Thanks!

**Comment by jwmueller** [comment]
Also this issue may already be resolved in our latest master branch. 
@coralexbadeaYonder If you have a chance it would be helpful if you can run cleanlab from the latest master branch on the same `labels`, `pred_probs` to see if the vague error message persists.

**Comment by coralexbadeaYonder** [comment]
Ok I verified and with the main branch it gives the proper output.

**Comment by jwmueller** [comment]
Great thank you for checking!
