### ISSUE TITLE
CleanLab correct class suggestion

### ISSUE THREAD

**Issue by coralexbadeaYonder** [cleanlab/cleanlab#337]
Is there any way CleanLab can tell you for faulty labeled samples which class is most likely to be the correct one?

**Comment by cgnorthcutt** [comment]
Hi @coralexbadeaYonder! Have you tried https://cleanlab.ai/studio/ for this? This is exactly what Cleanlab Studio is for -- to help you correct issues versus just finding issues. If your data is text/tabular/csv/excel -- you can use it today. Image/audio support is coming later this year.

**Comment by coralexbadeaYonder** [comment]
Ok got it. I am looking forward to try CleanLab Studio for images later this year. Thank you!
