### ISSUE TITLE
Features Changes

### ISSUE THREAD

**Issue by 315386775** [cleanlab/cleanlab#341]
from cleanlab.classification import LearningWithNoisyLabels

ImportError: cannot import name 'LearningWithNoisyLabels' from 'cleanlab.classification'

the version changes?

**Comment by 315386775** [comment]
the new version change to CleanLearning, yes?

**Comment by jwmueller** [comment]
Yep! You can refer to our migration guide here:  https://docs.cleanlab.ai/v2.0.0/migrating/migrate_v2.html
