### ISSUE TITLE
how to get the confidence and predit label

### ISSUE THREAD

**Issue by 315386775** [cleanlab/cleanlab#346]
`ranked_label_issues = find_label_issues(
    train_label,
    val_preds,
    return_indices_ranked_by="self_confidence",
)`

use the find_label_issues can get ranked_label index. i also want to get the error image's predicted label and confidence. how can i get it. thanks.

**Comment by jwmueller** [comment]
You can directly get these things for all examples from the `val_preds` numpy array of predicted class probabilities via:
```
predicted_confidence = val_preds.max(axis=1)
predicted_classes = val_preds.argmax(axis=1)
```

Then you can just subset these arrays to only keep the indices corresponding to `ranked_label_issues`.

**Comment by jwmueller** [comment]
You can alternatively get all this information as well as find the label issue indices, all in one line of code, if you are able to use our CleanLearning class for your application:

https://docs.cleanlab.ai/v2.0.0/tutorials/indepth_overview.html#Workflow-1:-Use-CleanLearning()-for-everything

Note CleanLearning does not apply to all data-types or classifiers though, whereas what I mentioned in my previous comment will.

**Comment by 315386775** [comment]
thanks. i got it.
