### ISSUE TITLE
Jupyter notebook tutorials: Show full plots without scroll-bars

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#356]
Figure out how to get nbsphinx to display the plots in full-size without scroll bars

**Comment by JanuRam** [comment]
@jwmueller Is this issue still open?

**Comment by jwmueller** [comment]
@JanuRam yes you can see many of the plots in our rendered documentation tutorials, eg:

https://docs.cleanlab.ai/master/tutorials/datalab/datalab_quickstart.html

have scroll bars. We would like the full plots to be visible on the website without scroll bars, you will likely need to change some nbsphinx settings to make this happen
