### ISSUE TITLE
Analysis of data labeled by multiple annotators

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#374]
- [x] Adding functionality to: estimate quality of current consensus labels, estimate quality of each annotator, obtain the best possible consensus labels.
- [x] Add quickstart tutorial.
- [x] Add example demonstrating iterative usage of multi-annotator functionality to iteratively improve consensus labels and model, but don't merge it while links are not ready.

**Comment by cgnorthcutt** [comment]
Test on amazon magazine reviews dataset.  (real-world, high quality multiple annotations)
