### ISSUE TITLE
Jupyter notebook tutorials: <div> Notebook cells that look nice in Github

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#382]
Many of our Jupyter notebooks have special formatted blocks. Cf:

![Image](https://user-images.githubusercontent.com/1390638/187634362-0d228e0f-46a4-4c7c-9b3d-a1a96a99eb30.png)
https://github.com/cleanlab/cleanlab/blob/master/docs/source/tutorials/image.ipynb

These good in Jupyter and in Colab, but look ugly in Github display of the notebook (eg. the above link) due to the \</div\> tag.
Would be nice to make these cells simultaneously look good in Github display as well as Jupyter and Colab.

**Comment by huiwengoh** [comment]
Issue is because `markdown="1"` tags in the div block are not being rendered properly in github.

Spend a good amount of time investigating and can't seem to find a way to fix it, but it seems like we are not the only one to have this issue (eg. [the nbsphinx docs](https://github.com/spatialaudio/nbsphinx/blob/0.8.9-5-gfc79fd1/doc/markdown-cells.ipynb)).
Also tried using non-markdown syntax in the html div block but couldn't find an alternative that looks good on docs site.

**Comment by jwmueller** [comment]
No worries thanks for trying!  I also figured it might not be easily achievable.

**Comment by jwmueller** [comment]
How about let's discourage usage of such <div> blocks in examples notebooks (which I suspect many people are simply viewing in Github) ? 

I'll add a note to examples/DEVELOPMENT.md

**Comment by jwmueller** [comment]
@huiwengoh Could you instead find an alternate format for the examples notebooks \<div\> blocks and make an update to them? We just want these blocks to look good in: github viewer and in Jupyter.  It is less important that they have the special \<div\> / alert / colored style, so you could convert them to standard markdown cells if you like, optionally including any markdown technique you can think of to make them stand out.

I only found this block in our [multiannotator example](https://github.com/cleanlab/examples/blob/master/10_cifar10_multiannotator/multiannotator_labels.ipynb) but there may be others in other example notebooks if you can check! 

![Screen Shot 2022-09-11 at 3 30 16 PM](https://user-images.githubusercontent.com/1390638/189551557-dd937fcf-31ec-4bfc-be72-3b8e4461dd56.png)

**Comment by huiwengoh** [comment]
Examples notebook reformat done here: https://github.com/cleanlab/examples/pull/16

**Comment by huiwengoh** [comment]
Randomly stumbled across this so just leaving it here for reference. It is a known case that the info/warning boxes does not work nicely with GitHub's notebook preview:
[https://nbsphinx.readthedocs.io/en/0.8.9/markdown-cells.html#Info/Warning-Boxes](https://nbsphinx.readthedocs.io/en/0.8.9/markdown-cells.html#Info/Warning-Boxes)

Perhaps [this issue](https://github.com/jupyter/notebook/issues/1292) (also linked in that docs page) will have some updates in the future to make it look nicer.
