### ISSUE TITLE
Add support for Ordinal Classification/Regression tasks

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#387]
This is fairly straightforward extension of the current cleanlab functionality.  Contributors welcomed!

**Comment by JanFidor** [comment]
Hi @jwmueller ! This issue looks quite exciting, is it still up for grabs? I'm crossing my fingers, so I'll also ask just in case it is. Would [this approach](https://www.cs.waikato.ac.nz/~eibe/pubs/ordinal_tech_report.pdf) be ok? (Benchmarks seem to be showing a consistent improvement over naive approaches)

**Comment by jwmueller** [comment]
@JanFidor yes that sounds great! Note you would want to extend `cleanlab.filter.find_label_issues()` and `cleanlab.rank.get_label_quality_scores()` to the ordinal classification setting, assuming the user has trained their ordinal classifier model in the way outlined in your reference paper from Frank & Hall.

You'll want to put the analogous methods in a new module:
`cleanlab.ordinal_classification.filter.find_label_issues()`
``cleanlab.ordinal_classification.rank.get_label_quality_scores()`

Make sure you also report a benchmark of how good the label error detection is vs. simply doing standard classification + `cleanlab.filter.find_label_issues()` or  `cleanlab.rank.get_label_quality_scores()` (i.e. just detecting the label errors as if the problem were a standard multi-class classification task)
