### ISSUE TITLE
color_sentence matches subtokens 

### ISSUE THREAD

**Issue by elisno** [cleanlab/cleanlab#388]
`color_sentence`  technically does subtoken matching instead of checking for equality between the tokenized sentence and the given token.

Is this intended?

# Stack trace

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: ('\x1b[31mI\x1b[0mf you and I were to meet', 'If you and \x1b[31mI\x1b[0m were to meet')
```

# Steps to reproduce

Here's a MWE

```python
from cleanlab.internal.token_classification_utils import color_sentence

sentence = "If you and I were to meet"
word = "I"
output = color_sentence(sentence, word)
expected_output = "If you and \x1b[31mI\x1b[0m were to meet"

assert output == expected_output, (output, expected_output)
```

# Additional information

- **Cleanlab version**: 31d43707014cb5c217ee1e9b014a206d554f2fd3
- **Operating system**: Linux 4.19.128-microsoft-standard
- **Python version**: Python 3.9.12

## Definition of `color_sentence`

https://github.com/cleanlab/cleanlab/blob/31d43707014cb5c217ee1e9b014a206d554f2fd3/cleanlab/internal/token_classification_utils.py#L144-L164

**Comment by elisno** [comment]
Any thoughts on this @ericwang1997?

**Comment by ericwang1997** [comment]
The function currently searches for the first occurrence of the substring in the sentence, so it will be problematic if we're searching for tokens as generic as "I". There are two ways to get around this: 

1. Add an optional argument to take in the given tokens. Using your example, the user will call: 
```
tokens = ["If", "you", "and", "I", "were", "to", "meet"]
color_sentence(sentence, word, tokens=tokens) 
```
or simply generate the sentence internally using `get_sentence` and call: 
``` 
color_sentece(word, tokens) 
``` 
2. Tokenize the sentence and search for the keyword token. Or simply search for `" " + word " "`. The first option is more ideal imo.

**Comment by elisno** [comment]
Thanks for those suggestions.

I agree that providing tokenized text instead to the function as it's only called by `display_issues` which has the tokenized data at hand.


> The code below covers that case

Thanks! I think it's best I'd redefine `color_sentence` this way as you suggest, add the MWE as a test case and update the function call in `display_issues` accordingly!

**Comment by jwmueller** [comment]
^ Sounds like good plan to me!  Also if the word occurs multiple times in token-list, should `color_sentence()` color all instances of the word?  Or why is coloring only the first instance more desirable?

**Comment by ericwang1997** [comment]
Good call. The keyword typically appears only once in the sentence as long as it's specific enough, but highlighting all occurrences makes more sense (it might be easier to extend this functionality using the new version of `color_sentence()` above)
