### ISSUE TITLE
docs: mis-rendered summary/details

### ISSUE THREAD

**Issue by anishathalye** [cleanlab/cleanlab#440]
The collapsible summary/details in the notebooks look a bit broken. Looking at the HTML in the rendered result, looks like the `<summary>` tag is being replaced with a `<p>` tag. Also, I think we should standardize our summary text across the docs.

Some examples of broken behavior:

Image tutorial: says "Details" instead of "Below is the code used for plotting":

Collapsed:

<img width="825" alt="Screen Shot 2022-09-14 at 10 10 03 AM" src="https://user-images.githubusercontent.com/3526486/190177634-3b102b98-66bc-4092-a209-4d47f0be8700.png">

Expanded:

<img width="867" alt="Screen Shot 2022-09-14 at 10 10 27 AM" src="https://user-images.githubusercontent.com/3526486/190177670-384c2b46-8d37-4012-bd2b-4786f046d264.png">

Token classification tutorial: has the right text but an unnecessary newline:

<img width="866" alt="Screen Shot 2022-09-14 at 10 11 01 AM" src="https://user-images.githubusercontent.com/3526486/190177796-da98d2b7-1d32-4629-87d9-978f6cd83441.png">

I like the way we've formatted it on our [blog](https://cleanlab.ai/blog/cleanlab-vizzy/), with the text "(click to expand)" included there:

<img width="501" alt="Screen Shot 2022-09-14 at 10 11 50 AM" src="https://user-images.githubusercontent.com/3526486/190178086-7a72409d-9c20-4e64-accf-bf166a4501e5.png">

Another nit, we should have `cursor: pointer` for the `<summary>`.

Also, it could be helpful to delineate the block with a border-top and border-bottom, so after it's expanded, the reader knows where the details end.

**Comment by jwmueller** [comment]
FYI if trying to show the “summary” field in [docs.cleanlab.ai](http://docs.cleanlab.ai/), you’ll need to update all the text in those fields. The current text “Below is …” is written with the assumption the summary is not being shown on [docs.cleanlab.ai](http://docs.cleanlab.ai/).  It would not make sense for docs.cleanlab.ai to say "Below is ..." with all the stuff below actually hidden.
