### ISSUE TITLE
Linking to docs of private function

### ISSUE THREAD

**Issue by huiwengoh** [cleanlab/cleanlab#451]
In #449 `cleanlab.token_classification.rank.softmin_sentence_score` was made private. But there are docs referencing this private function and the docstring for it is not visible so just the functional name shows up on [docs.cleanlab.ai](url):

![image](https://user-images.githubusercontent.com/45724323/190542693-71e400df-30ec-47f1-b329-b18bbaa570bb.png)

On a separate thought, unsure if this should be a private function given we allow users to pass in kwargs for it - would they know what kwargs to pass in if the function is private?

**Comment by jwmueller** [comment]
I think it's ok for now, @elisno and I are just a bit wary to commit to a particular API for these helper methods so early on. We can always make this not private once we are more confident in that API. And anyway only advanced users should ever specify this (I'll make that clear in follow-up token-classification docstring improvements PR), who should be capable of looking up the source code directly.

**Comment by huiwengoh** [comment]
Ah alright, thanks for the clarification! Was just unsure if it was something that was missed in that PR. 
Closing this issue then (quick one!)
