### ISSUE TITLE
Docs: figure out why previous version did not appear in sidebar of docs.cleanlab.ai

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#467]
Specifically in the index.html, search.html files, I manually added v2.0.0 version link in sidebars when we released v2.1.0.  But this should be there automatically in future releases.

- [ ] Ensure similar updates are applied in:
  - [ ] stable version files 
  - [ ] master version files
  - [ ] older version files for each older version (eg. v1.0.1 docs should also have link to v2.0.0)
- [ ] build "staging" version of docs where we can test effects of tagged release and test your changes work.
- [ ] Push this update to cleanlab repo and verify docs.cleanlab.ai looks good

**Comment by elisno** [comment]
Previous versions were manually added to https://github.com/cleanlab/cleanlab/blob/master/docs/source/_templates/versioning.html.

This means that older versions of the docs can't automatically get forward links to newer versions.
