### ISSUE TITLE
in LearningWithNoisyLabels(), did it train only on confident results? (by dropping label errors found by cleanlab)? 

### ISSUE THREAD

**Issue by cindyyj** [cleanlab/cleanlab#47]
Dear Curtis, 

I am a bit confused. in LearningWithNoisyLabels(), did it train only on confident results? (by dropping label errors found by cleanlab)? 

I found in your state-of-the-art on CIFAR-10 application, cleanlab is used to find the label errors in CIFAR-10, and then Remove errors and train on cleaned data via Co-Teaching... 

Hope to learn your approach better. Thank you very much!

**Comment by dac19980925** [comment]
maybe you should read the paper

**Comment by anishathalye** [comment]
Yes, `LearningWithNoisyLabels` prunes data points identified by `find_label_issues()`. See https://github.com/cleanlab/cleanlab/blob/9a3eb368814f4dd04192e6d612b0c282d76fd9ac/cleanlab/classification.py#L388-L398.
