### ISSUE TITLE
[Short summary of the question]

### ISSUE THREAD

**Issue by AmA514** [cleanlab/cleanlab#486]
Hello, I am a new user of CleanLab. When I tried to use Image Classification with PyTorch and Cleanlab 
in https://docs.cleanlab.ai/stable/tutorials/image.html. 
I replaced the MNIST dataset with the local dataset (CIFAR 10), leaving the rest unchanged. 
After I have completed cross_val_predict and generated pred_probs(numpy.ndarray with (50000,10)), run to:
---------------------------------------------------------------------------
from cleanlab.filter import find_label_issues

ranked_label_issues = find_label_issues(
    labels,
    pred_probs,
    return_indices_ranked_by="self_confidence",
)
An error was encountered:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_1467/1626596905.py in <module>
      1 from cleanlab.filter import find_label_issues
      2 
----> 3 ranked_label_issues = find_label_issues(
      4     labels,
      5     pred_probs,

~/autodl-tmp/my_task1/cleanlab/filter.py in find_label_issues(labels, pred_probs, return_indices_ranked_by, rank_by_kwargs, filter_by, multi_label, frac_noise, num_to_remove_per_class, min_examples_per_class, confident_joint, n_jobs, verbose)

~/autodl-tmp/my_task1/cleanlab/internal/validation.py in assert_valid_inputs(X, y, pred_probs, multi_label, allow_missing_classes)

~/autodl-tmp/my_task1/cleanlab/internal/validation.py in assert_valid_class_labels(y, allow_missing_classes)

AttributeError: 'bool' object has no attribute 'any'

Thank you for your help.

**Comment by jwmueller** [comment]
How are your `labels` formatted?  Could you provide complete code example as well as information on which version of cleanlab you are running?

You can also check each of the requirements listed here regarding the format of `labels`:  https://docs.cleanlab.ai/stable/tutorials/faq.html#How-do-I-format-classification-labels-for-cleanlab?

**Comment by AmA514** [comment]
> How are your `labels` formatted? Could you provide complete code example as well as information on which version of cleanlab you are running?
> 
> You can also check each of the requirements listed here regarding the format of `labels`: https://docs.cleanlab.ai/stable/tutorials/faq.html#How-do-I-format-classification-labels-for-cleanlab?

Thank you! In `labels`,  I confused str() with int(). It has now been solved.
