### ISSUE TITLE
ValueError: labels must be 1D numpy array in multi_label setup

### ISSUE THREAD

**Issue by janmejaya-nanda** [cleanlab/cleanlab#516]
`find_label_issues` in `multi_label=True` setup expects labels to be an 1D array. while [the document](https://docs.cleanlab.ai/stable/cleanlab/filter.html#cleanlab.filter.find_label_issues) suggests it should be a list of lists(or a 2D array). the complete stack trace is provided below, please let me know if I misunderstood anything.

I think the issue lies somewhere in the indices ranking code, as it runs smoothly if `return_indices_ranked_by` is set to default(i.e. `None`).

# Stack trace

```
Traceback (most recent call last):
  File "check_labels.py", line 81, in <module>
    ranked_label_issues = find_label_issues(
  File "/home/.virtualenv/lib/python3.8/site-packages/cleanlab/filter.py", line 390, in find_label_issues
    er = order_label_issues(
  File "/home/.virtualenv/lib/python3.8/site-packages/cleanlab/rank.py", line 90, in order_label_issues
    assert_valid_inputs(X=None, y=labels, pred_probs=pred_probs, multi_label=False)
  File "/home/.virtualenv/lib/python3.8/site-packages/cleanlab/internal/validation.py", line 42, in assert_valid_inputs
    assert_valid_class_labels(y=y, allow_missing_classes=allow_missing_classes)
  File "/home/.virtualenv/lib/python3.8/site-packages/cleanlab/internal/validation.py", line 110, in assert_valid_class_labels
    raise ValueError("labels must be 1D numpy array.")
ValueError: labels must be 1D numpy array.
```

# Additional information

- **Cleanlab version**: cleanlab==2.1.0
- **Operating system**:  Ubuntu 20.04
- **Python version**: Python 3.8.2

**Comment by jwmueller** [comment]
Thanks for pointing out that bug! We are actually about to release v2.2 with major improvements to the multilabel classification functionality, and this bug should already have been fixed in that effort.

You can try using the latest master branch of cleanlab to test it your self: 
```pip install git+https://github.com/cleanlab/cleanlab.git```
and then run the same code you were running before

**Comment by jwmueller** [comment]
@janmejaya-nanda Believe this should be fixed in the latest master branch, but feel free to reopen this issue if not!
