### ISSUE TITLE
Return "margin" for false-classifications

### ISSUE THREAD

**Issue by nneubauer** [cleanlab/cleanlab#54]
It would be great if `get_noise_indices()` would not only return the ordered indices but also the ordering criteria (so eg. the `margin`). Maybe returned as a tuple or have another function that returns both in order not break the API.

I am looking to convey a "confidence" that a label is a wrong classification.

**Comment by cgnorthcutt** [comment]
Great idea! And should be easy to do. Could you send a pull request with the change?

**Comment by sshkhr** [comment]
If this is still of interest I can send a PR with the required change @cgnorthcutt

**Comment by anishathalye** [comment]
This is a great idea, and the upcoming Cleanlab 2.0 release will include such functionality. It was added in c50836cfbfa24651e01ac408286addad21704225 by @JohnsonKuan. You can see the documentation for [`get_label_quality_scores`](https://docs.cleanlab.ai/master/cleanlab/rank.html#cleanlab.rank.get_label_quality_scores) for more information.

If you want to use this today, you could install the unreleased 2.0 from source. We should be releasing 2.0 within a couple of days.

(See also, #73)
