### ISSUE TITLE
Multi-label Classification, getting Y class error.

### ISSUE THREAD

**Issue by kumar10725** [cleanlab/cleanlab#55]
Good day,
I am trying to use cleanlab to train a multi-label classifier, where my target classes are encoded using scikit-learn MultiLabelBinarizer[link here](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MultiLabelBinarizer.html). 
I have a total of five classes and 20,000 images for training. 
I build up a scikit-learn BaseEstimator and wrap a Keras Resnet50 model inside it.
Now when using LearningWithNoisyLabels from cleanlab.classification , I am getting following error:

```Traceback (most recent call last):
  File "c:/Users/ASUS/Desktop/cleanlab mangoes/clean_training.py", line 16, in <module>
    lnl.fit(X, y)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\cleanlab\classification.py", line 267, in fit
    assert_inputs_are_valid(X, s, psx)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\cleanlab\util.py", line 41, in assert_inputs_are_valid
    ensure_2d=False,
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\sklearn\utils\validation.py", line 807, in check_X_y
    y = column_or_1d(y, warn=True)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\sklearn\utils\validation.py", line 847, in column_or_1d
    "got an array of shape {} instead.".format(shape))
ValueError: y should be a 1d array, got an array of shape (25767, 5) instead.
```

my code used for training is as follow:

```
from sk_resnet import ResnetTrainer
from cleanlab.classification import LogReg
from cleanlab.classification import LearningWithNoisyLabels
import pandas as pd 

df = pd.read_csv('train_labels.csv')
values = df.values
X = values[:,0]
y = values[:,1:]


lnl = LearningWithNoisyLabels(clf=ResnetTrainer(batch_size=8, epochs=10))
lnl.fit(X, y)
```

I hope authors of cleanlab can provide a simple example of how to use cleanlab for multi-label training.

**Comment by LiangTIAN97** [comment]
When I use cleanlab in multi-label task, I get following error:
![image](https://user-images.githubusercontent.com/49553288/111075486-148bfc00-8523-11eb-9b5f-eec1d948f7ba.png)
![image](https://user-images.githubusercontent.com/49553288/111075491-1c4ba080-8523-11eb-9f7e-a0f6f2dc9c71.png)
My code is as follow:
![image](https://user-images.githubusercontent.com/49553288/111075501-32f1f780-8523-11eb-8d93-7a4ea6efed57.png)

**Comment by cgnorthcutt** [comment]
Hi @LiangTIAN97 what happens if you format `s` as a list of lists?

**Comment by LiangTIAN97** [comment]
> Hi @LiangTIAN97 what happens if you format `s` as a list of lists?

I format s as a list, I still get error:
![image](https://user-images.githubusercontent.com/49553288/111096549-c0146b00-857a-11eb-9129-8da5e0e3fe75.png)
![image](https://user-images.githubusercontent.com/49553288/111096558-c73b7900-857a-11eb-81e9-73412283202f.png)
![image](https://user-images.githubusercontent.com/49553288/111096684-0ec20500-857b-11eb-9e21-e0c404828c95.png)

**Comment by cgnorthcutt** [comment]
@LiangTIAN97 Can you paste the code (instead of screenshot). I'll try it out.

**Comment by cgnorthcutt** [comment]
@LiangTIAN97 Also, which version of numpy are you using?

**Comment by LiangTIAN97** [comment]
> @LiangTIAN97 Can you paste the code (instead of screenshot). I'll try it out.

from cleanlab.pruning import get_noise_indices
import numpy as np

s = [[2],
     [1],
     [0,2],
     [0],
     [1],
     [2],
     [1,2]]
psx = np.array([[0.1,0.1,0.9],
        [0.1,0.8,0.1],
        [0.6,0.1,0.9],
        [0.6,0.1,0.1],
        [0.1,0.8,0.1],
        [0.1,0.1,0.9],
        [0.1,0.9,0.9]])

ordered_label_errors = get_noise_indices(
   s=s,
   psx=psx,
   sorted_index_method='normalized_margin', # Orders label errors
 )
print(ordered_label_errors)

**Comment by LiangTIAN97** [comment]
> @LiangTIAN97 Also, which version of numpy are you using?

My numpy version is 1.11.3. Is it because of the inappropriate version?

**Comment by cgnorthcutt** [comment]
@LiangTIAN97 You were just missing a parameter `multi_label=True` in `get_noise_indices()`

In future versions of cleanlab, it will detect this automatically, but for now, you still need to specify it.

Use this code. It produces the expected error:

```python
from cleanlab.pruning import get_noise_indices
import numpy as np

# Add this if you want to detect errors with less than 5 examples in the class
from cleanlab import pruning
pruning.MIN_NUM_PER_CLASS = 1

s = [[2],
[1],
[0,2],
[0],
[1],
[2],
[1,2]]
psx = np.array([[0.1,0.1,0.9],
[0.1,0.9,0.0],
[0.5,0.0,0.5],
[0.6,0.1,0.1],
[0.1,0.8,0.1],
[0.9,0.1,0.0],
[0.1,0.9,0.9]])

ordered_label_errors = get_noise_indices(
s=s,
psx=psx,
sorted_index_method='normalized_margin', # Orders label errors
multi_label=True,
)
print(ordered_label_errors)
```

**Comment by cgnorthcutt** [comment]
I'll plan to mark this as closed, unless there are any other issues?

**Comment by LiangTIAN97** [comment]
> I'll plan to mark this as closed, unless there are any other issues?

There is no issues. Thanks for your help!

**Comment by cgnorthcutt** [comment]
Keeping this open as a reminder to implement direct support for multi-labels in LearningWithNoisyLabels() classifier.

**Comment by fernandocamargoai** [comment]
Hello, @cgnorthcutt. Any plans for when LearningWithNoisyLabels will support multi-label?

**Comment by jwmueller** [comment]
In cleanlab v2.2, we did a major overhaul of the functionality for multi-label classification. All of these issues should now be resolved, and cleanlab's new label error detection capabilities for multi-label classification are much more powerful and easy to use!

Get started here: https://docs.cleanlab.ai/stable/tutorials/multilabel_classification.html

And definitely please open a new issue (stating which cleanlab version you are using) if you still encounter any problems using cleanlab for multi-label datasets.
