### ISSUE TITLE
TypeError: ufunc 'true_divide' appeared unexpectedly when trying to run the code again

### ISSUE THREAD

**Issue by m23chaffee** [cleanlab/cleanlab#554]
I'm trying to get the average of a data set in a table that I have sorted from the data pool I found (for my school exercise). I tried this code yesterday and it give me a desired result.

`avg = np.average(elastic)
print ("The mean of the aluminum alloy is", avg)`

However, when I'm trying to finished my work and run the code again, it gave me this stack trace

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_88\1108074980.py in <module>
----> 1 avg = np.average(elastic)
      2 print ("The mean of the aluminum alloy is", avg)

<__array_function__ internals> in average(*args, **kwargs)

~\anaconda3\lib\site-packages\numpy\lib\function_base.py in average(a, axis, weights, returned)
    378 
    379     if weights is None:
--> 380         avg = a.mean(axis)
    381         scl = avg.dtype.type(a.size/avg.size)
    382     else:

~\anaconda3\lib\site-packages\numpy\core\_methods.py in _mean(a, axis, dtype, out, keepdims, where)
    189             ret = ret.dtype.type(ret / rcount)
    190     else:
--> 191         ret = ret / rcount
    192 
    193     return ret

TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

I don't know what I did wrong and I haven't found any answers on the net that works in my situation. I have read the numpy documentation regarding numpy.average, but still stuck. I have also tried search for YouTube for answers, but it lead me nowhere. 

The attached file is the complete file I'm currently working. 

[Working Exercise.pdf](https://github.com/cleanlab/cleanlab/files/10145368/Working.Exercise.pdf)

**Comment by jwmueller** [comment]
I think you've opened your github issue on the wrong repo. The issues here are for cleanlab questions. 

For questions about numpy, open a github issue on their repo here: 
https://github.com/numpy/numpy
