### ISSUE TITLE
Missing link in documentation

### ISSUE THREAD

**Issue by jss367** [cleanlab/cleanlab#611]
The documentation on this page: https://docs.cleanlab.ai/stable/index.html have a link for "label errors" that it found, but that link points to https://labelerrors.com/, which doesn't seem to be a site. I'm assuming there is supposed to be a different link here.

**Comment by jwmueller** [comment]
Thanks for pointing this out.  labelerrors.com is supposed to be a website characterizing many label errors found in the major ML benchmark datasets, the website just seems to have recently gone down for some reason.

**Comment by jwmueller** [comment]
labelerrors.com website is back up now, thanks to @anishathalye !
