### ISSUE TITLE
Whether cleanlab can be used for object detection?

### ISSUE THREAD

**Issue by BruceSonBo** [cleanlab/cleanlab#622]
I am currently working on the object detection task.  Could you please convert the object detection into a classification task before using cleanlab?

**Comment by jwmueller** [comment]
Hi @BruceSonBo, We don't have dedicated functionality for object detection tasks yet, but our team is actively working on it and should be ready around end of the month! Our roadmap is publicly available here: https://github.com/orgs/cleanlab/projects/2/views/1

In the meantime, one easy heuristic way to handle object detection is as a multi-label classification task: https://docs.cleanlab.ai/stable/tutorials/multilabel_classification.html

For each image, you just ask the question: does this image contain an object of class k, yes or no, for each possible class k.
This forms a multi-label classification label for the image (that ignores the locations of the bounding boxes). 
You can estimate predicted class probabilities for this task from an existing detector model via the probabilities of each box's classes output by your model, eg. saying the probability of class k for the image is the maximum probability of class k for any one of the boxes predicted by your detector model. (Recall the probabilities need not sum to 1 over k for multi-label classification).

Running cleanlab in this way can find some images that have annotation errors in our experience, but we have been doing research on even better algorithms, stay tuned!

**Comment by jwmueller** [comment]
Another possibility is to run cleanlab on small sub-grids of the image treated as separate examples, as outlined here:
https://github.com/cleanlab/cleanlab/issues/586#issuecomment-1371736594

There I outlined it for image segmentation, but the principle for detection is quite similar.

**Comment by BruceSonBo** [comment]
thanks for your reply, I've done experiments and it works, but it's not very accurate

**Comment by Correr-Zhou** [comment]
Hi, Jonas.
Have you released the related "CleanLab" code for object detection?
I can't wait to use it! : )

**Comment by jwmueller** [comment]
For those interested in detecting label errors in object detection data, we have a PR for this functionality here: https://github.com/cleanlab/cleanlab/pull/676/

So you can see our progress live. Once that is merged, you can find label errors in any object detection dataset using any trained model you have.

**Comment by jwmueller** [comment]
Cleanlab can now be used for object detection:  https://docs.cleanlab.ai/master/tutorials/object_detection.html
