### ISSUE TITLE
Fix label issues when model does not predict some class ever

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#639]
Some users have reported bugs in two situations. Investigate these to verify bugs exist and then address any that come up.

1) When there exists some class k, such that the model never predicts class k for any of the examples in the dataset.
2) When there exists some class k such that pred_probs[:,k] == 0 for all examples whose given label is k. Then the confident_thresholds[k] == 0 which can lead to abnormalities.

One simple fix for case 2, is if `pred_probs[:,k] == 0` for all examples, then can just delete this column from the pred_probs. Subsequently can simply delete all examples with label k from the dataset before finding label issues, keeping track of the how indices in the reduced dataset correspond to indices in the original dataset.

**Comment by cgnorthcutt** [comment]
For clarity, the issue occurs when the model always predicts zero probability for some class. This happens sometimes when a class is underrepresented. When this happens, the class threshold for that class is zero. That means every example s probability is greater than or equal to that class. That means every example always is confidently guessed as that class as the true class. That means anytime that example is actually confidently guessed as some other class, the algorithm will think it's confidently two classes. When that happens this line of code (screenshot) will just choose the argmax prediction, this reducing all label error detection methods to just choosing the argmax (the most naive approach)

![Screenshot_20230302-193902.png](https://user-images.githubusercontent.com/27030270/222625631-4d536a71-aaa0-4b5c-b061-fc51aab7d1cf.png)



Super simplest naive solution is don't allow class thresholds that are zero. (Clip at 1e-6)

**Comment by jwmueller** [comment]
Fixed in https://github.com/cleanlab/cleanlab/pull/647
