### ISSUE TITLE
cleanlab/filter.py:974: UserWarning: May not flag all label issues in class 

### ISSUE THREAD

**Issue by xiaokening** [cleanlab/cleanlab#641]
When I use cleanlab to detect label issue in multi-label classification, The following problem occurs many times，

warnings.warn(
/opt/conda/envs/nlp/lib/python3.8/site-packages/cleanlab/filter.py:974: UserWarning: May not flag all label issues in class: 1, it has too few examples (see `min_examples_per_class` argument)

the format of labels and pred_probs follows official guidelines。

**Comment by jwmueller** [comment]
In general, you will see this warning if there are some classes which occur very rarely in your dataset. You can safely ignore the warning if you already know you have these extremely rare classes (cleanlab will anyway not be able to very accurately identify label errors in really rare classes as there isn't enough data to learn much about them). 

You can try setting `min_examples_per_class=0` to make this warning go away. 

FYI if working with multi-label data, be sure you are using cleanlab >= 2.2.0. We made some major improvements to the underlying algorithms in this version:  https://cleanlab.ai/blog/multilabel/

To receive additional assistance, we will need more details from you. If you still need help, could you provide more details like what version of cleanlab are you using, and a runnable example that reproduces this issue?

**Comment by xiaokening** [comment]
Thank you very much for your reply   @jwmueller 

But there is **another question** when I use cleanlab。

when I use  `cleanlab.filter .find_label_issues` in  in multi-label classification,  Only one CPU is utilized，the n_jobs params isn't set。

cleanlab = 2.2.0

**Comment by jwmueller** [comment]
Better use of multi-processing for multi-label datasets is being tracked here:
https://github.com/cleanlab/cleanlab/issues/298

For now, you can better speed-ups with multi-label datasets via:

`cleanlab.multilabel_classification.filter.find_label_issues(..., low_memory=True)`

https://docs.cleanlab.ai/stable/cleanlab/multilabel_classification/filter.html
