### ISSUE TITLE
Remove requirement for labels in Datalab

### ISSUE THREAD

**Issue by elisno** [cleanlab/cleanlab#675]
_Originally posted by @jwmueller in https://github.com/cleanlab/cleanlab/pull/614#discussion_r1172178871_

Datalab currently focues on labeled datasets for supervised learning.

Ideally, making the following change should lift that constraint and support unlabeled data:

```diff
class Datalab:
-    det __init__(self, data, label_name: str, ...):
+    det __init__(self, data, label_name: Optional[str] = None, ...):
        ...
```

but this may require more effort.

Some items that this affects:

- Some unit tests will break as they initialize Datalab with a labeled dataset.
- Need to discuss how to handle `Datalab(unlabeled_data).find_issues(pred_probs=pred_probs)`, mainly for label error detection.
  - Does (unsupervised) model support fit into this picture?

**Comment by jwmueller** [comment]
Closed by https://github.com/cleanlab/cleanlab/pull/730
