### ISSUE TITLE
About the use of Object Detection

### ISSUE THREAD

**Issue by tyraut** [cleanlab/cleanlab#727]
Hi ! I noticed that the object detection function has been added to cleanlab. How should I use it? I didn't find any tutorials or examples.Thanks!

**Comment by jwmueller** [comment]
It has not been added yet officially, it is in this PR which is not yet merged:
https://github.com/cleanlab/cleanlab/pull/676

You can install cleanlab from the PR and use the functionality though, the source code is 100% complete.
There is a tutorial for it in the PR here:  https://github.com/ulya-tkch/cleanlab/blob/uly-od/docs/source/tutorials/object_detection.ipynb

If you don't know how to install from PR or have other questions, then you are better off just waiting until we've merged the PR, as our team is hard at work polishing the tutorial and a paper about the methodology to make it easy for everybody to use.
