### ISSUE TITLE
Add GEN algorithm for Out-of-distribution detection based on pred_probs

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#728]
The [GEN paper](https://openaccess.thecvf.com/content/CVPR2023/papers/Liu_GEN_Pushing_the_Limits_of_Softmax-Based_Out-of-Distribution_Detection_CVPR_2023_paper.pdf) proposes an interesting generalized entropy function of the pred_probs that should be simple to add for cleanlab's OOD detection based on pred_probs:

https://docs.cleanlab.ai/stable/tutorials/outliers.html
https://cleanlab.ai/blog/ood-classifier/

Before officially adding this though, some benchmarking would be necessary. A simple way to benchmark is just to run these:
https://github.com/cleanlab/ood-detection-benchmarks

and compare with cleanlab's current pred_probs based OOD detection.

**Comment by coding-famer** [comment]
I'd be interested in working on this and took a look at the contributor guide. I will try to implement it in several weeks and benchmark it first.

**Comment by jwmueller** [comment]
awesome sounds good!  If you'd like a more real-time discussion of anything, feel free to ping in [slack](https://cleanlab.ai/slack/)

**Comment by jwmueller** [comment]
Completed in https://github.com/cleanlab/cleanlab/pull/800
