### ISSUE TITLE
Obtaining Scores For Pruned Data Instances

### ISSUE THREAD

**Issue by HareeshBahuleyan** [cleanlab/cleanlab#73]
Hi @cgnorthcutt, thanks for putting together this amazing library. 

I see the function `get_noise_indices` returns the indices of the instances in the dataset with high likelihood of having label errors. Since it returns a ranked list from the most erroneous index to the least, is there a way to retrieve the scores used for this ranking? For instance, the likelihood of index 1 having label error is 0.9, the likelihood of index 5 having label error is 0.4 and so on?

Thanks in advance!

**Comment by anishathalye** [comment]
This is a great idea, and the upcoming Cleanlab 2.0 release will include such functionality. It was added in c50836cfbfa24651e01ac408286addad21704225 by @JohnsonKuan. You can see the documentation for [`get_label_quality_scores`](https://docs.cleanlab.ai/master/cleanlab/rank.html#cleanlab.rank.get_label_quality_scores) for more information.

If you want to use this today, you could install the unreleased 2.0 from source. We should be releasing 2.0 within a couple of days.
