### ISSUE TITLE
Extend label issue detection in Datalab to work even without pred_probs input

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#735]
Goal: extend the label issue check in Datalab to work even if user only provided: `features`, `labels` to `Datalab.find_issues()`.

There are multiple ways this can be achieved:

Option 1 (easiest): Use sklearn `KNNclassifier` (or `LogisticRegression`) applied to `X=features, y=labels` in order to produce out-of-sample `pred_probs` and then continue as usual.

Option 2: Use methods from other papers like these (requires benchmarking them first):
- [SelfClean: A Self-Supervised Data Cleaning Strategy](https://arxiv.org/abs/2305.17048)
- [Detecting Corrupted Labels Without Training a Model to Predict](https://arxiv.org/abs/2110.06283)

**Comment by Steven-Yiran** [comment]
Hi @jwmueller, can I work on this? I plan to implement option 1 but also want to implement option 2 after that. Thanks!

**Comment by jwmueller** [comment]
@Steven-Yiran Yes would love your help with this!  

Going with option 1 sounds great. Make sure to keep big datasets in mind when prototyping this (ensure scalability), and don't forget the `pred_probs` our internal model produces based on the `features` need to be [out-of-sample](https://docs.cleanlab.ai/stable/tutorials/pred_probs_cross_val.html). 

Guide that describes how issue types work in Datalab (and how to add new issue types) is here:  https://docs.cleanlab.ai/master/cleanlab/datalab/guide/index.html

For this project, I think you can just extend the [LabelIssueManager](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/datalab/issue_manager/label.py) to still work even when only `features` and `labels` are provided but no `pred_probs`.  Whenever `pred_probs` is provided, it should take precedence and `features` should be ignored (ie. preseve current behavior of LabelIssueManager in this case).

@elisno Can also help you with questions, and feel free to reach out in [Slack](https://cleanlab.ai/slack) too!
