### ISSUE TITLE
a question about compute_confident_joint() method

### ISSUE THREAD

**Issue by cwings316** [cleanlab/cleanlab#737]
Hello, thank you for providing such a convenient confidence learning framework. 
Recently, I encountered an issue while studying the open-source code for confidence learning and I hope to get some clarification. 

In the `compute_confident_joint()` method, the implementation logic for calculating `true_label_guess` is as follows:

```
pred_probs_bool = pred_probs >= thresholds - 1e-6
num_confident_bins = pred_probs_bool.sum(axis=1)
more_than_one_confident = num_confident_bins > 1
pred_probs_argmax = pred_probs.argmax(axis=1)
confident_argmax = pred_probs_bool.argmax(axis=1)

true_label_guess = np.where(
        more_than_one_confident,
        pred_probs_argmax,
        confident_argmax,
    )
```
This code snippet represents the following logic:
For each example, choose the confident class (greater than threshold).
When there is 2+ confident classes, choose the class with largest prob.

However, it is possible that the class with the highest prob may not exceed the specified threshold.
For example, in a three-class scenario, the probability distribution of a certain sample is [0.4, 0.35, 0.25], and the threshold is [0.5, 0.2, 0.2]. 
According to the logic of this code, the `true_label_guess` would be class 0. BUT, the `true_label_guess` should be class 1.

Is what I'm saying correct? I hope to receive an answer from you. Thank you.

**Comment by jwmueller** [comment]
Can you clarify why `true_label_guess` = class 0 is not good in your opinion?  It seems fine IMO given predicted probabilities = [0.4, 0.35, 0.25]

**Comment by cwings316** [comment]
According to the Confidence Learning paper ([Northcutt et al., 2021](https://jair.org/index.php/jair/article/view/12125), Section 3.1, Equation 1), true_label_guess should be selected from the categories with probabilities greater than the threshold. 
In this example, the thresholds for the three categories are [0.5, 0.2, 0.2]. It can be seen that the probability for class 0 is not greater than the threshold 0.5.

**Comment by cgnorthcutt** [comment]
Hi @cwings316 , thanks for bringing this up, its a great question! We deviated slightly from the paper here primarily for simplicity and scalability (it matches up with benchmarks for several other pieces of the code).

Would you be open to running these [36 benchmarks (9 models, 4 datasets)](https://github.com/cleanlab/examples/blob/master/classifier_comparison/classifier_comparison.ipynb) for the following three cases and seeing if you can tell any significant (and reliable) improvement in performance for any of the three options?

The three options when there is a collision:
1. Return the argmax prob -- (currently in the code)
2. Return the argmax prob AMONG those that exceed the threshold -- (confident learning paper)
3. Return the argmax(prob - class threshold) -- (another option, not robust if there are classes the model does badly on, ie results will be baised to classes with low class thresholds)

What do you think, want to give this a shot @cwings316 ? I'd love to see what you find.
