### ISSUE TITLE
Using cross_val_predict

### ISSUE THREAD

**Issue by jankrepl** [cleanlab/cleanlab#74]
Great project @cgnorthcutt !

I am reading through the source code and if I am not mistaken you could "outsource" the following lines to `scikit-learn`.

https://github.com/cgnorthcutt/cleanlab/blob/ec735a06d93d2ce90ccb60d9b8a44b495169e159/cleanlab/latent_estimation.py#L613-L627

by using `cross_val_predict` ([docs](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_predict.html)) with `method="predict_proba"`.

Anyway, maybe I am not aware of potential differences. And of course, it is your call.

Cheers

**Comment by jwmueller** [comment]
Thanks for the pointer!  Cleanlab actually now does some more sophisticated things inside of this code (eg. to work with tensorflow/pytorch Datasets, rare classes, etc), so we cannot fully outsource it to `cross_val_predict`. 

But keep the suggestions coming!
