### ISSUE TITLE
Add support for Data Valuation with Shapely values

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#740]
Add a [new IssueManager in Datalab](https://docs.cleanlab.ai/stable/cleanlab/datalab/guide/custom_issue_manager.html) which provides support for the following task:

Estimate how valuable each datapoint is to a trained model, ie. how much model performance might drop if this datapoint were not included in training set. This can be done via [Data Shapely values](https://dcai.csail.mit.edu/lectures/data-centric-evaluation/), but they are in general inefficient to calculate. 

Luckily, Datalab already uses a K-nearest-neighbor graph, and Data Shapely is efficient to compute for KNN. 
So the goal is to add the KNN-specific efficient Shapely values, which just reuses the KNN graph that Datalab is already using to detect other types of data issues. 

Check out [this related PR](https://github.com/cleanlab/cleanlab/pull/760) which added support in Datalab to find label issues based on only `features` and `labels` (via a KNN classifier)

## References to learn more

Efficient Data Valuation with Exact Shapley Values
https://towardsdatascience.com/efficient-data-valuation-with-exact-shapley-values-f0689ff708e

Scalability vs. Utility: Do We Have to Sacrifice One for the Other in Data Importance Quantification?
https://arxiv.org/abs/1911.07128

## More Details
 
If working on this, please link to a fully runnable Jupyter notebook to test your code. 

The notebook should run:
1. datalab with your isuse-type using this efficient KNN shapely value. 
2. the naive shapely value where you just delete data and measure the resulting prediction-accuracy (use a KNN classifier here too)

1 and 2 should give similar data valuation results. Notebook should report runtimes and ensure 1 is significantly faster than 2.

**Comment by jmelot** [comment]
I'd be interested in working on this and took a look at the contributor guide. If you're accepting external contributions I'll try to submit a PR within the next week or two!

**Comment by jwmueller** [comment]
> I'd be interested in working on this and took a look at the contributor guide. If you're accepting external contributions I'll try to submit a PR within the next week or two!

Awesome @jmelot , Don't hesitate to ask questions you have!

In case you'd like to chat about anything in real-time in Slack:
https://cleanlab.ai/slack

I recommend first assuming the KNN graph has already been computed within Datalab (eg. by the outliers check) and just operating over the existing graph (simply because the initial code will be easier to correctly structure that way)

**Comment by jwmueller** [comment]
Another efficient method for Data Shapely and Data Valuation w arbitrary models that are not K nearest neighbors

[Data-OOB: Out-of-bag Estimate as a Simple and Efficient Data Value](https://arxiv.org/abs/2304.07718)

**Comment by jwmueller** [comment]
Done in https://github.com/cleanlab/cleanlab/pull/850
