### ISSUE TITLE
integrate mini-batch find_label_issues_batched as an option for methods that internally call find_label_issues

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#762]
Many methods throughout the package internally call [cleanlab.filter.find_label_issues](https://docs.cleanlab.ai/stable/cleanlab/filter.html#cleanlab.filter.find_label_issues). This method requires a significant amount of memory, so another version of this method has been created with much lower memory requirements that also runs faster: [cleanlab.experimental.label_issues_batched.find_label_issues_batched](https://docs.cleanlab.ai/stable/cleanlab/experimental/label_issues_batched.html#cleanlab.experimental.label_issues_batched.find_label_issues_batched)

This is achieved by computing the estimates via iterative mini-batching and certain approximations.

**Goal**: For each method that internally calls `filter.find_label_issues()`, we should offer an optional argument: `low_memory = False` by default, which if set to `True` internally calls `experimental.label_issues_batched.find_label_issues_batched()` instead.  Thus users who need to run things with reduced memory/runtime can simply specify `low_memory=True` in whichever  method they are using and internally it will run things differently to help them.

**Comment by tataganesh** [comment]
I am starting with the [find label issues](https://github.com/cleanlab/cleanlab/blob/63254c55b6afbfa3839ea54cdcd56b1cae718d1a/cleanlab/classification.py#L897C12-L897C12) for classification. From the description, I believe that the code would look something like - 
```python
if low_memory:
    label_issues_mask = find_label_issues_batched(
        labels, pred_probs)
else:
    label_issues_mask = filter.find_label_issues(
        labels,
        pred_probs,
        **self.find_label_issues_kwargs,
    )

```
Based on the datalab interface, how should `low_memory` be specified? Would it look something like this?

```python
lab = Datalab(data, label_name="y")
lab.find_issues(pred_probs=pred_probs, issue_types={"label": {"low_memory": True}})
``` 
or

```python
issue_types = {
    "label": {
        "clean_learning_kwargs": {
            "low_memory": True,
       }
  }
}

lab = Datalab(data, label_name="y")
lab.find_issues(pred_probs=pred_probs, issue_types=issue_types)
```
I am assuming that `low_memory` should just be an additional parameter to [CleanLearning.find_label_issues ](https://github.com/cleanlab/cleanlab/blob/63254c55b6afbfa3839ea54cdcd56b1cae718d1a/cleanlab/classification.py#L690C14-L690C14).

**Comment by jwmueller** [comment]
@tataganesh could you handle this: https://github.com/cleanlab/cleanlab/issues/855

Thanks!

**Comment by tataganesh** [comment]
The `low_memory=True` option has been added to all methods that call [cleanlab.filter.find_label_issues](https://docs.cleanlab.ai/stable/cleanlab/filter.html#cleanlab.filter.find_label_issues), so we should be good to close this issue.
