### ISSUE TITLE
How to change the TH method?

### ISSUE THREAD

**Issue by nadavpo** [cleanlab/cleanlab#767]
I want to change the TH (t_j from paper) method from average over confidence of classier for all class samples, to median or something else, how can I do that?
I try to change in `get_confident_thresholds` function in count.py file but I'm not sure its working, what else can I do?

**Comment by jwmueller** [comment]
Sorry we do not officially support altering this functionality at this time. To see why your code change is not having the intended effect, you will need to go through the stack trace and see why the method you have altered is not being called where you think it is.
