### ISSUE TITLE
Labels and Predictions Insertion to Cleanlab

### ISSUE THREAD

**Issue by hamzagorgulu** [cleanlab/cleanlab#771]
Hi there, I have a hard time to insert the labels and predictions that I get from the model. I train the model with detectron and get the predictions using it. I also convert the types by considering the object detection tutorial on github. Even though I have the exactly same type of input, the find_label_issues function does not accept it. Is there a guideline process from detectron predictions to cleanlab inputs?

Additionally, there is a semantic segmentation tutorial provided but I could not find one for instance segmentation. I would be happy if you direct me also about this. What could be the the tricks to convert it?

**Comment by jwmueller** [comment]
Hi @hamzagorgulu , you can see how we trained a Detectron2 object detection model and formatted its predictions for use with cleanlab in this example notebook:

https://github.com/cleanlab/examples/blob/master/object_detection/README.md

For us to help you further with this, you'll need to share what your current predictions look like, and what error message you are getting from cleanlab (and what your cleanlab code looks like).  Once you share that @ulya-tkch can help you debug further

**Comment by jwmueller** [comment]
We do not yet specifically support instance segmentation in this package yet.  Let us know if you’re able to get good results for instance segmentation using existing code, and we'd love to have you contribute something!

You should be able to use the existing code for semantic segmentation label error detection by converting your instance segmentation labels & predictions into semantic segmentation labels & predictions. That approach may not capture all possible types of label errors, but I'd guess it will work decently.

**Comment by ulya-tkch** [comment]
Hey @hamzagorgulu, were you able to run `find_label_issues()` for object detection on the data from your detectron model? Happy to help figure out the formatting issue if you provide me with the error message and an example of your current predictions and labels.

**Comment by hamzagorgulu** [comment]
Hey @ulya-tkch, thank you very much for interest. I was able to convert the outputs but now I am getting visualization issues. I try to visualize the samples randomly first but the annotations are wrongly drawn. My bounding boxes are already in xywh format, so I commented the [bbox_xyxy_to_xywh()](url) function. I also visualize the same image with labelImg and there is no problem with it. Here is the code I visualize the random samples:
`for idx in range(5):
    #breakpoint()

    image_to_visualize = random.randint(0,len(labels))
    image_path = os.path.join(IMAGE_PATH , labels[image_to_visualize]['seg_map'])
    label = labels[image_to_visualize]
    print(image_path, '| idx', image_to_visualize , "| bounding box: ", label["bboxes"])
    class_names = get_classes()
    visualize(image_path, label=labels[idx], prediction=predictions[idx], overlay=False, class_names=class_names) # maybe write your own function.`
And here is a sample output:
![image](https://github.com/cleanlab/cleanlab/assets/67511748/2e38fd52-3c13-4f05-97f9-42c4e409dbc7)


After I find the issue indexes, I also visualize them with this code block:
`for idx in range(10):
    issue_to_visualize = issue_idx[random.randint(0,len(issue_idx))]  # change this to view other images

    #breakpoint()

    label = labels[issue_to_visualize]
    prediction = predictions[issue_to_visualize]
    score = scores[issue_to_visualize]
    image_path = os.path.join(IMAGE_PATH , label['seg_map'])
    #breakpoint()

    print(image_path, '| idx', issue_to_visualize , '| label quality score:', score, '| is issue: True', "| bounding box: ", label["bboxes"])
    visualize(image_path, label=label, prediction=prediction, class_names=class_names, overlay=False)`

This visualizes the ground truth bboxes correct, but sometimes moves the predicted image like this:
![image](https://github.com/cleanlab/cleanlab/assets/67511748/1620d9c2-e444-480d-85be-c38af9172187)

**Comment by jwmueller** [comment]
Hi @hamzagorgulu , I assume the new code works for you. If not, please re-open this issue and share details of the problem you are facing!
