### ISSUE TITLE
Supporting task-specific issues in Datalab

### ISSUE THREAD

**Issue by elisno** [cleanlab/cleanlab#774]
While cleanlab has added support for various types of ML tasks, The only task-specific check supported by `Datalab` is label error detection for classification.

## Proposed Changes

The most straightforward approach to supporting new tasks, such as regression, is to write a new issue manager.

We propose several changes to extend `Datalab`’s functionality for different tasks (focusing on supporting classification and regression for now).

- [ ]  Define a `RegressionLabelIssueManager` for checking for label issues in regression tasks.
    - Add this into a separate `label.py` module in a new directory, like shown below.
        
        ```diff
        cleanlab/cleanlab/datalab/issue_manager/
        + ├── regression
        + │   └── label.py
        ├── __init__.py
        ├── duplicate.py
        ├── imbalance.py
        ├── issue_manager.py
        ├── label.py
        ├── noniid.py
        └── outlier.py
        ```
        
    - For simplicity, the issue manager and its `find_issues` method should take in whatever necessary arguments. Don’t worry about supporting different `model`s for now.
        - Take a close look at `regression.CleanLearning.find_label_issues`.
- [ ]  Add an argument to the Datlab constructor for specifying a task
    
    ```bash
    # Add argument and store as an instance variable
    Datalab.__init__(..., ml_task: str = "classification")
    ```
    
- [ ]  Make` _IssueManagerFactory` methods accept an argument for tasks
- [ ]  Update classes that use `_IssueManagerFactory` to pass task-argument from `Datalab` to the factory methods.

**Comment by mglowacki100** [comment]
Hi @elisno 

To be on the same page regarding `Datalab` class modification, do you mean something like this:
```
class Datalab:
    def __init__(self, option):
        self.task = option

    def find_issues(self, *args, **kwargs):
        if self.task == 'classification':
            self._find_issues_classification(*args, **kwargs)
        elif self.task == 'regression':
            self._find_issues_regression(*args, **kwargs)
        else:
            print("Invalid option!")

    def _find_issues_classification(self, arg1=None, arg2=None):
        ...

    def _find_issues_regression(self, arg3=None):
        ...
```

**Comment by elisno** [comment]
Hey @mglowacki100.

Thank you for your thoughtful input. I appreciate the effort you've put into solving this issue.

I've considered your approach of having separate task-specific registries for classification and regression tasks, and while this could work, I believe it may introduce some complexity, especially when we need to add more tasks in the future.

Instead, I propose an alternate approach where we maintain two types of registries: a general `REGISTRY` and a `TASK_SPECIFIC_REGISTRY` registry. The general `REGISTRY` will hold non-task-specific issue managers (like `OutlierIssueManager`, `NearDuplicateIssueManager`, and `NonIIDIssueManager`) that are common across all tasks, while the `TASK_SPECIFIC_REGISTRY` registry will hold issue managers that are specific to a particular task.

Here's a rough idea:

```python
REGISTRY: Dict[str, Type[IssueManager]] = {
    "outlier": OutlierIssueManager,
    "near_duplicate": NearDuplicateIssueManager,
    "non_iid": NonIIDIssueManager,
}

TASK_SPECIFIC_REGISTRY: Dict[str, Dict[str, Type[IssueManager]]] = {
    "classification": {
        "label": LabelIssueManager,
    },
    "regression": {
        "label": RegressionLabelIssueManager,
    },
}
```

The `from_str` and `from_list` class methods of the _IssueManagerFactory should first look into the task-specific registry based on the given task. If it's not found, the factory looks into the general registry. This approach allows us to cleanly separate task-specific and general issue managers while keeping the logic for looking up the managers simple and straightforward. 

Other classes/functions depend on `REGISTRY`, so we'd have to update those to consider both registries.

- The `IssueFinder` class uses/refers to the REGISTRY for listing out possible/default issue types. These could consider the task as well.
- The `register` function only accepts an `IssueManager`, but not it should also allow for tasks. New issue managers should be registered in the regular REGISTRY by default, but if a task is given, it's added to the `TASK_SPECIFIC_REGISTRY`.

However, on the `Datalab` side of things, we'll still set the default task to be classification as an instance variable.

---

> Next is to make the task an argument for IssueFinder class and build it depending on REGISTRY type. Also Datalab would have a task argument, that would be passed to IssueFinder in find_issues method. Does it make sense?


This idea does make sense. However, with the proposal above, the `_IssueManagerFactory` should handle choosing from the correct registry based on the task. The `IssueFinder` passes the task on to the factory.

A clear way to proceed with incorporating the task: inject the task into the `IssueFinder` when instantiating it. This way the task type is clear and explicit. I think it would be easier to maintain this way.



I appreciate your insights and suggestions! I'm open to any further thoughts you may have on this approach.

**Comment by elisno** [comment]
Regarding your second point:

> here I can provied precomputed pred_probs; why for regression I can't provide something analogous like pred_ys?

The `find_label_issues` method in our `CleanLearning` class for regression tasks involves a more involved estimation process, which makes allowing arbitrary predictions tricky. It's not just a matter of getting cross-validated predictions.
For now, this led us to the decision to handle the predictions internally for the regression case.

I hope this provides some insight into the current design! If you have further queries or need more details, please feel free to ask.

**Comment by mglowacki100** [comment]
Hi @elisno 
I've made draft PR with proposed changes in architecture, for now `label.py` for regression is mocked up. It passes all the tests with default task "classification" but it fails on ImageLab integration, that is a new thing. I'll try to figure it out.
