### ISSUE TITLE
Could this work for token classification (NER)?

### ISSUE THREAD

**Issue by HoopsMcann** [cleanlab/cleanlab#78]
I assume that each row in psx would correspond to a token/word and the columns would be the entities I care about. My concern is that the number of rows may be too large. For example, in my dataset I have about 500K words.

**Comment by fabiocapsouza** [comment]
I'm also interested in trying to use it for NER and I'm having similar doubts. Have you tried it?
I think it might need some adjustments, since AFAIK cleanlab removes bad examples from the dataset, but in this case each example is an entity and it cannot be removed independently. 

For 500K words I think it is possible, since cleanlab was used with ImageNet which has 1M examples and 1K classes. It might need a lot of RAM, though

**Comment by HoopsMcann** [comment]
Exactly, its not clear how to handle the bad examples/tokens that cleanlab finds. One idea would be to remove sequences that have a certain threshold of token errors detected. So if half the tokens in sequence were bad examples then remove the sequence from the dataset.

Yes, it works for 500k words I hadn't seen the imagenet example before posting this..oops.

**Comment by cgnorthcutt** [comment]
This is an exciting use case. I bet you could help the cleanlab community greatly (and folks would be interested in your result) if you share a minimum working example once you settle on a method to remove 'bad' sequences for individual tokens.

I see two options:
1. remove entire sequence and allow for waste.
2. a secondary process to deal with bad tokens (requires creativity!)

And yup, as you noticed, cleanlab can work for millions of examples. See labelerrors.com where we use cleanlab on Quickdraw which has **50 million** images. The machine had about 110GB RAM, although you can process the dataset in chunks if needed.

**Comment by HoopsMcann** [comment]
Thanks @cgnorthcutt I will definitely work on this!

**Comment by addisonklinke** [comment]
Related question - could `cleanlab` work for optical character recognition (OCR)? 

Based on reading this thread, I think the answer is yes. An OCR model takes image pixels and outputs a sequence of classifications (i.e. choosing the most likely token class at each timestep). Similar to NER, I would have to treat the predicted + labeled token at each timestep as a paired sample, and pick an appropriate strategy for pruning sequences as noted by @cgnorthcutt  above. The dimension of the joint distribution `Q` would be the number of tokens in the model's vocabulary. 

One difficulty I foresee is variable length sequences. Should I consider off-diagonal elements in the `Q` matrix which correspond to padding (represented by `*`)? For instance, if the noisy label is `AB123*` but the model confidently predicts `ABC123` then at the 3rd timestep the sequences are misaligned. I suppose one option is to only do the confident counting step if the unpadded label and prediction are the same length

**Comment by HoopsMcann** [comment]
@rpowalski yes and no, I've made some progress but got busy with work before I could come up with anything substantial. It's in my backlog as of now.

**Comment by jwmueller** [comment]
We will be releasing a simple tutorial on using cleanlab for sequence prediction tasks like NER, OCR shortly, stay tuned!

**Comment by lluissalord** [comment]
@jwmueller If there is a tutorial for using cleanlab on sequence prediction tasks, could you please post here the link in order to find it easily? Thanks!

**Comment by jwmueller** [comment]
@lluissalord Yes I will post it here when we've completed it! It will probably take at least a month

**Comment by cgpeltier** [comment]
Interested in this as well, in case this was completed!

**Comment by cgnorthcutt** [comment]
We have a new algorithm in the works that let's cleanlab scale to tens of thousands of classes efficiently, making it work for word and token level analysis.

We plan to release this as part of v2.1 later this year. Pretty excited about it :)

**Comment by cgnorthcutt** [comment]
@cgpeltier We have a new algorithm in the works that let's cleanlab scale to tens of thousands of classes efficiently, making it work for word and token level analysis.

We plan to release this as part of v2.1 later this year. Pretty excited about it :)

**Comment by rpowalski** [comment]
@jwmueller awesome initiative to make it work with NER models. Any chance that you have this tutorial ready?

**Comment by jwmueller** [comment]
Yes @rpowalski we'll have something for you start looking at next week!
