### ISSUE TITLE
how to deal with the data whose is_near_duplicate_issue is True to improve the robustness of my model.[Short summary of the question]

### ISSUE THREAD

**Issue by xiaokening** [cleanlab/cleanlab#805]
After I use cleanlab to find near_duplicate_issue of my data, I don't know how to deal with the data whose is_near_duplicate_issue is True(these data are indeed near duplicated) to improve the robustness of my model.

Can I just delete the data whose is_near_duplicate_issue is True ？ will it cause all near_duplicate data deleted ? And not keep one of them?

**Comment by jwmueller** [comment]
Yes that will delete all near_duplicate data, so you probably want to keep at least one of each. See the [Datalab tutorial](https://docs.cleanlab.ai/stable/tutorials/datalab/datalab_quickstart.html#Near-duplicate-issues) on how to get the `near_duplicate_sets` which you can use to ensure at least one of each datapoints remains in dataset.

Note whether or not simply deleting near-duplicates from the dataset is appropriate or not will depend on your application, so consider it carefully!

**Comment by xiaokening** [comment]
@jwmueller Yes, I know about near_duplicate_sets, but I need to manually confirm which sample to keep, which is quite a tedious process.

I want to use an automated algorithm to delete the data with near_duplicate_issue and keep one of the near_duplicate_sets. Just like label_issue, outlier, non_iid, I can quickly delete data through a boolean value.

The following is an algorithm I wrote, this algorithm can ensure that the data I delete is near_duplicate data and keep one of them, but I am not sure if there is any problem with this algorithm. Can you give me some advice? Thanks!



```
"""
data(pandas.DataFrame):has is_near_duplicate_issue、near_duplicate_score、distance_to_nearest_neighbor field
"""
max_near_duplicate_score = max(data.loc[data.is_near_duplicate_issue==True, "near_duplicate_score"])
near_duplicate_sets = []

#find near_duplicate_set list
for i in tqdm(data.index):
    if data.loc[i, "is_near_duplicate_issue"]:
        if data.loc[i, "near_duplicate_score"] <=max_near_duplicate_score:
            near_duplicate_e = data.loc[i, "near_duplicate_sets"][0]
            near_duplicate_sets.append({i, near_duplicate_e})

def merge_list(L):
    """
    Merge set that contain the same elements in a list
    """
    lenth = len(L)
    for i in range(1, lenth):
        for j in range(i):
            if L[i] == {"x"} or L[j] == {"x"}:
                continue
            x = L[i].union(L[j])
            y = len(L[i]) + len(L[j])
            if len(x) < y:
                L[i] = x
                L[j] = {"x"}

    return [i for i in L if i != {"x"}]

near_duplicate_sets = sorted(map(sorted, map(list, merge_list(near_duplicate_sets))), key=lambda x:x[0]) # sorted

is_remove_duplicate_flag = []
id_list = []
for s in near_duplicate_sets:
    l = len(s)
    is_remove_duplicate_flag += [True] * (l - 1) + [False]
    id_list += list(s)

data["is_remove_duplicate_data"] = False
data.loc[id_list, "is_remove_duplicate_data"] = pd.Series(is_remove_duplicate_flag, index=id_list)
data["is_remove_duplicate_data"] = data.apply(lambda x: True if x["is_remove_duplicate_data"] and x["is_near_duplicate_issue"] else False, axis=1)
```

**Comment by elisno** [comment]
Hi @xiaokening 

> I want to use an automated algorithm to delete the data with near_duplicate_issue and keep one of the near_duplicate_sets. Just like label_issue, outlier, non_iid, I can quickly delete data through a boolean value.

I appreciate your initiative in wanting to automate the process for handling near duplicate data in your dataset.

> The following is an algorithm I wrote, this algorithm can ensure that the data I delete is near_duplicate data and keep one of them, but I am not sure if there is any problem with this algorithm. Can you give me some advice? Thanks!

You're on the right track of trying to merge the duplicate sets to have distinct groups of near duplicates before throwing all-but-one out.

I have made a generalizable code snippet to help you identify unwanted indices based on near duplicate sets in your dataset.

You can paste the following code snippet into the [Datalab quickstart tutorial notebook (on Colab)](https://colab.research.google.com/github/cleanlab/cleanlab-docs/blob/master/v2.4.0/tutorials/datalab/datalab_quickstart.ipynb) in a new cell at the bottom.

```python
from typing import Callable

def merge_duplicate_sets(df, merge_key: str):
    """Generate group keys for each row, then merge intersecting sets."""

    df[merge_key] = df.apply(construct_group_key, axis=1)
    merged_sets = consolidate_sets(df[merge_key].tolist())
    df[merge_key] = df[merge_key].map(
        lambda x: next(s for s in merged_sets if x.issubset(s))
    )
    return df

def construct_group_key(row):
    """Convert near_duplicate_sets into a frozenset and include the row's own index."""
    return frozenset(row['near_duplicate_sets']).union({row.name})

def consolidate_sets(sets_list):
    """Merge sets if they intersect."""
    
    # Convert the input list of frozensets to a list of mutable sets
    sets_list = [set(item) for item in sets_list]
    
    # A flag to keep track of whether any sets were merged in the current iteration
    merged = True

    # Continue the merging process as long as we have merged some sets in the previous iteration
    while merged:
        merged = False
        new_sets = []

        # Iterate through each set in our list
        for current_set in sets_list:
            # Skip empty sets
            if not current_set:
                continue

            # Find all sets that have an intersection with the current set
            intersecting_sets = [s for s in sets_list if s & current_set]

            # If more than one set intersects, set the merged flag to True
            if len(intersecting_sets) > 1:
                merged = True

            # Merge all intersecting sets into one set
            merged_set = set().union(*intersecting_sets)
            new_sets.append(merged_set)

            # Empty the sets we've merged to prevent them from being processed again
            for s in intersecting_sets:
                sets_list[sets_list.index(s)] = set()

        # Replace the original sets list with the new list of merged sets
        sets_list = new_sets

    # Convert the merged sets back to frozensets for the output
    return [frozenset(item) for item in sets_list]

def lowest_score_strategy(sub_df):
    """Keep the row with the lowest near_duplicate_score."""
    return sub_df['near_duplicate_score'].idxmin()


def filter_near_duplicates(data: pd.DataFrame, strategy_fn: Callable = lowest_score_strategy, **strategy_kwargs):
    """
    Given a dataframe with columns 'is_near_duplicate_issue' and 'near_duplicate_sets',
    return a series of boolean values where True indicates the rows to be removed.
    The strategy_fn determines which rows to keep within each near_duplicate_set.

    :param data: DataFrame with is_near_duplicate_issue and near_duplicate_sets columns
    :param strategy_fn: Function to determine which rows to keep within each near_duplicate_set
    :return: Series of boolean values where True indicates rows to be removed.
    """
    
    # Filter out rows where 'is_near_duplicate_issue' is True to get potential duplicates
    duplicate_rows = data.query("is_near_duplicate_issue").copy()

    # Generate group keys for each row and merge intersecting sets
    group_key = "sets"
    duplicate_rows = merge_duplicate_sets(duplicate_rows, merge_key=group_key)

    # Use the strategy function to determine the indices of the rows to keep for each group
    to_keep_indices = duplicate_rows.groupby(group_key).apply(strategy_fn, **strategy_kwargs).explode().values

    # Produce a boolean series indicating which rows should be removed
    to_remove = ~data.index.isin(to_keep_indices)

    return to_remove


# Example Usage
near_duplicate_issues = lab.get_issues("near_duplicate").query("is_near_duplicate_issue").sort_values("near_duplicate_score")
ids_to_remove_series = filter_near_duplicates(near_duplicate_issues)
```

I want to emphasize the importance of determining a selection strategy tailored to your specific use case and goals.
I show you one example strategy above (`lowest_score_strategy`) to hopefully get you started. You're not restricted to strategies that throw out all near duplicates except one.

Here are some strategies that could make sense:

- Highest/lowest score (doesn't necessarily have to be near_duplicate_score).
- Keep the row with the smallest distance to its nearest neighbor (first). It's the same as the near_duplicate_score in this example.
- Select based on chronological order (if your examples are time-stamped).
- Prefer complete examples over those with missing values.
- Select at random.
