### ISSUE TITLE
extend non-iid issue check in Datalab

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#808]
Currently Datalab's non-iid issue type is only detected based on `features`:
https://docs.cleanlab.ai/master/cleanlab/datalab/guide/issue_type_description.html#non-iid-issue

If the user does not input `features`, but does provide` pred_probs`, run this same check based on the `pred_probs` instead (just treat them as features). 

Note that if the user did provide `features` or there was already a KNN graph constructed in Datalab, the results should be returned as they currently are, not using the `pred_probs` at all!

Reference:  https://github.com/cleanlab/cleanlab/blob/master/cleanlab/datalab/internal/issue_manager/noniid.py

**Comment by abhijitpal1247** [comment]
@jwmueller can you assign this issue to me?

**Comment by elisno** [comment]
Hi @abhijitpal1247!

Excited to see you tackle this issue! 🚀

### Quick tasks:

1. **Leverage `pred_probs`:** If no features, use `pred_probs` for the non-IID check.
2. **Maintain Current Logic:** Stick with existing logic if features or a KNN graph are provided.
    - The issue manager internally uses a `knn_graph` and implicitly accepts one via the `**kwargs`, so there's no reason to touch that part of the code.
3. **Refactor Thoughtfully:** Notice that `features` is used in a specific part of the [code](https://github.com/cleanlab/cleanlab/blob/6d45971cf83ccc85ac31d2591c54ce6b52a27281/cleanlab/datalab/internal/issue_manager/noniid.py#L127)?
    - Extracting common code might be a wise move to avoid repetition! Only worry about refactoring code that would rely on `pred_probs` as well.
4. **Tests and Docs:** Let’s validate and document any new paths in our logic.

Do the tasks make sense? 🤔 Feel free to drop any questions or thoughts below.

**Comment by abhijitpal1247** [comment]
@elisno created a PR #857
