### ISSUE TITLE
function to explore object detection datasets

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#809]
Assuming object detection data in the same format as required by methods in:
https://github.com/cleanlab/cleanlab/tree/master/cleanlab/object_detection 

Add functionality to explore basic properties about this data. For instance to compute:

1.  The number of annotated objects in each image, the number of predicted objects in each image. Users can sort by these to reveal interesting insights about certain images. Eg. number of images with 0 annotations may be particularly revealing.

2.  The sizes of every annotated bounding box. Users could look at boxplot/histogram and outliers here to reveal interesting insights about certain annotations. In particular, looking at the size-distribution of boxes labeled as each particular class.

3.  The distribution of classes associated with each annotated bounding box. Users could look for rare classes to better understand their dataset.
 
 Plus other useful things to explore!

**Comment by Steven-Yiran** [comment]
hi @jwmueller, I am interested in working on this issue.

**Comment by jwmueller** [comment]
@Steven-Yiran awesome! 

@ulya-tkch and @aditya1503 can additionally share some other ideas they've had for this too. If you prefer, we can have a real-time discussion in the #code-contributors channel in our [Community Slack](https://cleanlab.ai/slack)

**Comment by ulya-tkch** [comment]
Hi @Steven-Yiran, thanks for your interest :) 
Below I have compiled some info that might help you get started/give you some more ideas:

- Using `auxiliary_inputs = _get_valid_inputs_for_compute_scores(alpha, labels, predictions)` should return a dictionary containing all the information contributor needs for implementing some of this base functionality. For more info: `auxiliary_inputs` are a list where i-th element is a dictionary `auxiliary_input_dict` containing information on the i-th example's labels and predictions. Each  `auxiliary_input_dict` has the following keys which can be used to calculate items 1,2,3 in the issue:
```python3
auxiliary_input_dict: AuxiliaryTypesDict = {
        "pred_labels": pred_labels,
        "pred_label_probs": pred_label_probs,
        "pred_bboxes": pred_bboxes,
        "lab_labels": lab_labels,
        "lab_bboxes": lab_bboxes,
        "similarity_matrix": similarity_matrix,
        "iou_matrix": iou_matrix,
        "min_possible_similarity": min_possible_similarity,
}
```
- For testing of your code, you can either use the `make_data()` function in `tests/test_object_detection.py` or our example dataset in the [ObjectLab Tutorial](https://docs.cleanlab.ai/master/tutorials/object_detection.html) as both should be formatted correctly. Feel free to test on other data as well (and please let us know if you find any good datasets for this step!)
- The list of properties described above is not exhaustive. Another idea is to also add a dataset level report which reports per class accuracy, number of predicted/annotated instances per class, ect. 

Feel free to reach out to me here or in the Community Slack if you have any questions.

**Comment by Steven-Yiran** [comment]
Hi @ulya-tkch, thanks a lot for the information.  This will be enough to get me started!

**Comment by elisno** [comment]
> hi @jwmueller, is anyone working on it or can i work on this issue?

Hi @TuhsarChaudhary, this issue is currently being worked on in #840.
