### ISSUE TITLE
Extend Datalab to multi-label classification datasets

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#812]
Allow Datalab to find label issues when `labels` is multi-label object.

Related things to look at:

Extending Datalab to other ML tasks:
https://github.com/cleanlab/cleanlab/issues/774
https://github.com/cleanlab/cleanlab/issues/765
https://github.com/cleanlab/cleanlab/pull/796

Existing Datalab code for label issues:
https://github.com/cleanlab/cleanlab/blob/master/cleanlab/datalab/internal/issue_manager/label.py

Existing Cleanlab code for multi-label classification label issues:
https://github.com/cleanlab/cleanlab/tree/master/cleanlab/multilabel_classification

Adding new issue manager in Datalab:
https://docs.cleanlab.ai/master/cleanlab/datalab/guide/custom_issue_manager.html

**Comment by jwmueller** [comment]
Note from @elisno 

Datalab sets a `multi_label` statistic in the `DataIssues` attribute, which is designed to run existing cleanlab algorithms for auditing multi-label data. 

Actually running those algorithms from Datalab is what needs to be implemented here.

**Comment by 01PrathamS** [comment]
hello @jwmueller can i start working on this issue.

**Comment by jwmueller** [comment]
@01PrathamS Great!  Start by closely reading through this PR: 
https://github.com/cleanlab/cleanlab/pull/796

to understand what extending Datalab to a new ML task type looks like. 
I wouldn't open your PR for this new functionality until https://github.com/cleanlab/cleanlab/pull/796 is merged.
At that time, you'll have the clearest picture of how such an extension needs to look exactly, and what steps are required in the process.

**Comment by 01PrathamS** [comment]
will do as you suggested.

**Comment by 01PrathamS** [comment]
Hello @jwmueller @elisno , I have carefully reviewed #796 , ```cleanlab.multilabel_classification``` and  familiarize myself more with the code base. May I proceed with working on this? Additionally, are there any specific guidelines or notes you would like me to consider? I am committed to doing my best to enhance and complete this task.

**Comment by jwmueller** [comment]
Awesome @01PrathamS !

You can try to work on this, but it will be pretty complex, as a heads up. Make sure you feel very comfortable with related PRs like this: 
https://github.com/cleanlab/cleanlab/pull/902


Otherwise you could help us with easier issues like this one: 
https://github.com/cleanlab/cleanlab/issues/908
