### ISSUE TITLE
constraint for argmax(pred_probs) removed?

### ISSUE THREAD

**Issue by shpp9212** [cleanlab/cleanlab#823]
Hi,
I'm sorry if someone already asked the same question.
Regarding the following simplified compute_confident_joint function provided in cleanlab/count.py ,
(or, in the same sprit, the actual implementation below)
when num_confident_bins > 1, shouldn't the argmax computed only among those classes satisfying the threshold condition?

It seems the subscript condition in the following expression in the original confident learning paper is missing.

Please also let me know if my understanding is wrong!

![image](https://github.com/cleanlab/cleanlab/assets/83270709/c85d6a66-d4af-41ef-8b37-792dc76406bc)

###
        confident_joint = np.zeros((K, K), dtype = int)
        for i, row in enumerate(pred_probs):
            s_label = labels[i]
            confident_bins = row >= thresholds - 1e-6
            num_confident_bins = sum(confident_bins)
            if num_confident_bins == 1:
                confident_joint[s_label][np.argmax(confident_bins)] += 1
            elif num_confident_bins > 1:
                confident_joint[s_label][np.argmax(row)] += 1

###
    pred_probs_bool = pred_probs >= thresholds - 1e-6
    num_confident_bins = pred_probs_bool.sum(axis=1)
    at_least_one_confident = num_confident_bins > 0
    more_than_one_confident = num_confident_bins > 1
    pred_probs_argmax = pred_probs.argmax(axis=1)
    # Note that confident_argmax is meaningless for rows of all False
    confident_argmax = pred_probs_bool.argmax(axis=1)
    # For each example, choose the confident class (greater than threshold)
    # When there is 2+ confident classes, choose the class with largest prob.
    true_label_guess = np.where(
        more_than_one_confident,
        pred_probs_argmax,
        confident_argmax,
    )

**Comment by shpp9212** [comment]
Hi, I came up with the following issue, which is essentially the same question.
https://github.com/cleanlab/cleanlab/issues/737

So it seems that the implementation is indeed deviated from the original paper.
Has there been any conclusion on this issue?

**Comment by jwmueller** [comment]
Yes this codebase is continuously improving whereas the paper is a static object. 

If you find the implementation from paper works substantially better on your dataset than the code here, please let us know!

Check out this repo if specifically interested in code related to the paper:

https://github.com/cgnorthcutt/confidentlearning-reproduce

**Comment by jwmueller** [comment]
Feel free to reopen this issue if you still have any specific questions.
