### ISSUE TITLE
Improve Memory Efficiency for find_label_issues_batched method

### ISSUE THREAD

**Issue by elisno** [cleanlab/cleanlab#853]
### Summary
This issue aims to track the enhancement proposal to improve memory efficiency for the [`find_label_issues_batched` method](https://github.com/cleanlab/cleanlab/blob/6d45971cf83ccc85ac31d2591c54ce6b52a27281/cleanlab/experimental/label_issues_batched.py#L59).

### Problem
Users with large segmentation data have experienced memory issues due to the need for loading large datasets into memory with the current implementation of `find_label_issues_batched`.

### Suggested Solution
At a high level, a proposed solution is to make the method more memory-efficient by modifying it to iterate over images instead of points and ensuring that `flatten_and_preprocess` is called internally.

### Related Context
[Issue #842](https://github.com/cleanlab/cleanlab/issues/842) discusses the memory issues faced by a user when using the `find_label_issues` method on large datasets for segmentation.

**Comment by jwmueller** [comment]
Sorry this GH issue is mis-specified, our team is working to fix it to be properly specified. The `cleanlab/experimental/label_issues_batched.py` method has nothing to do with images, and should not be altered specifically for image data.

In the meantime, please refer to this issue:
https://github.com/cleanlab/cleanlab/issues/842

and try to find a fix outside of the `label_issues_batched.py` methods.

**Comment by jwmueller** [comment]
we will reopen this once it is properly specified

**Comment by jwmueller** [comment]
New issue to track this problem is here: 
https://github.com/cleanlab/cleanlab/issues/863
