### ISSUE TITLE
Allow dimension of X to be more than 2 (ValueError: Found array with dim 4. Estimator expected <= 2)

### ISSUE THREAD

**Issue by kothari1997narayan** [cleanlab/cleanlab#86]
https://github.com/cleanlab/cleanlab/blob/e10d93a6af69882ad317af99926e66bde353db72/cleanlab/util.py#L55

If we use a CNN model as a classifier then it will require X to have more than 2 dimensions
But in this check_X_y of sklearn utils take default argument of **allow_nd(Whether to allow X.ndim > 2) as false**. 
So, it will throw an error( **ValueError: Found array with dim 4. Estimator expected <= 2**) and we won't be able to use any CNN models.

I think you should give this option to user or set this parameter to **True** in cleanlab/util.py#L55

**Comment by anishathalye** [comment]
Great idea, thanks! Addressed in #148.
