### ISSUE TITLE
Improve efficiency and runtimes or memory usage (performance optimization)

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#862]
Try to speed up the runtime of certain methods, or reduce how much memory they use.

This is a great issue to get started contributing to this repo! There are many ways to achieve speedup. It is easy to verify speedup via basic benchmarking that also ensures the results remain the same after you have edited a method.

Start by running one specific method on a big dataset and profiling it thoroughly to see where the code bottlenecks are.

Known methods where big speedups can likely be obtained include all methods in:

1. [`cleanlab.multiannotator`](https://docs.cleanlab.ai/master/cleanlab/multiannotator.html)
2. [`cleanlab.multilabel_classification`](https://docs.cleanlab.ai/master/cleanlab/multilabel_classification/)
3. [`cleanlab.segmentation`](https://docs.cleanlab.ai/master/cleanlab/segmentation/index.html)
4. [`cleanlab.object_detection`](https://docs.cleanlab.ai/master/cleanlab/object_detection/index.html)
5. [Datalab NonIIDIssueManager](https://docs.cleanlab.ai/master/cleanlab/datalab/internal/issue_manager/noniid.html)

**Comment by arvind-swami** [comment]
DO you have any handy large real-world multiannotator dataset I can use?

**Comment by jwmueller** [comment]
> DO you have any handy large real-world multiannotator dataset I can use?

There are some multiannotator datasets here:

https://github.com/cleanlab/multiannotator-benchmarks

https://github.com/cleanlab/examples/blob/master/multiannotator_cifar10/multiannotator_cifar10.ipynb
