### ISSUE TITLE
What's the difference between number of issues in `health_summary` vs. `find_label_issues`?

### ISSUE THREAD

**Issue by gordon-lim** [cleanlab/cleanlab#866]
I am getting different results from the number of issues reported in `cleanlab.dataset.health_summary` versus the number of issues found using `cleanlab.filter.find_label_issues`. I was wondering what was the difference.

**Comment by ulya-tkch** [comment]
Hi @gordon-lim, thanks for opening up this issue. Can I get more information about your setup to better answer your question?
- What version of cleanlab are you using? What OS are you running this with?
- What kind of parameters are you calling `cleanlab.dataset.health_summary(..?)` with?
- What kind of parameters are you calling `cleanlab.filter.find_label_issues(..?)` with?
- What kind of dataset? What is the score discrepancy (i.e. is `find_label_issues` number of issues higher or lower than the one listed in the health summary?)

**Comment by gordon-lim** [comment]
Hi @ulya-tkch!

- I am using version 2.4.0 on M1 MacOS.
- I am calling both `health_summary` and `find_label_issues` with the same parameters: `noisy_labels` and `pred_probs`
- It is an image classification dataset. `find_label_issues` with the default `filter_by` gives about 400 and the one listed in `health_summary` gives over 600.

**Comment by ulya-tkch** [comment]
Hi @gordon-lim, thank you for bringing this up to my attention. I have an update on the `dataset.health_summary()` function coming in #875 which should make the two returned scores equivalent if you call it with `pred_probs` and `labels`. 

Originally, `dataset.health_summary()` simply estimated the number of label issues in a dataset and was an upper bound on `filter.find_label_issues()` which did the entire calculation. I updated it to return the real count of the number of issues.

Let me know if that does not fix your issue!

**Comment by gordon-lim** [comment]
That makes sense to me! Thank you for the response! I honestly thought I had missed on a new paper from your team introducing a new method for count estimation. Anyways, I'm glad it's being fixed! Thanks again!
