### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by kothari1997narayan** [cleanlab/cleanlab#87]
I tried implementing a simple **Keras** model, model description is mentioned below

>     input_img = Input(shape=(1350,))
>     x = Dense(units=32, activation='relu')(input_img)
>     x = Dropout(0.2)(x)
>     x = Dense(units=10, activation='relu')(x)
>     x = Dense(units=4, activation='softmax')(x)
>     model2 = keras.Model(input_img, x)
>     model2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

Then wrapped it with the sklearn **BaseEstimator**
Also edited a line in utils.py to not check for shapes of X and Y(https://github.com/cleanlab/cleanlab/blob/master/cleanlab/util.py#L55)

>     from sklearn.base import BaseEstimator
> 
>     class YourFavoriteModel(BaseEstimator): # Inherits sklearn base classifier
>     
>         def __init__(self, model):
>             self.model = model
>         
>         def fit(self, X, y):
>             yt = to_categorical(y, num_classes=4)
>             self.model.fit(X,yt, epochs=20, shuffle=True)
>         
>         def predict(self, X):
>             return np.argmax(self.model.predict(X,axis=-1))
>     
>         def predict_proba(self, X):
>             return self.model.predict(X)
>                          
>         def score(self, X, y, sample_weight=None):
>             yt = to_categorical(y, num_classes=4)
>             return self.model.evaluate(X,yt)[1]
> 
>     from cleanlab.classification import LearningWithNoisyLabels
>     lnl = LearningWithNoisyLabels(clf=YourFavoriteModel(model2))
>     lnl.fit(X_train, y_train)

But while doing the fit operation getting **TypeError: cannot pickle '_thread.RLock' object**
Detailed error is printed below..

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-2af841381025> in <module>
     23 from cleanlab.classification import LearningWithNoisyLabels
     24 lnl = LearningWithNoisyLabels(clf=YourFavoriteModel(model2))
---> 25 lnl.fit(X_train, y_train)

~\AppData\Roaming\Python\Python38\site-packages\cleanlab\classification.py in fit(self, X, s, psx, thresholds, noise_matrix, inverse_noise_matrix)
    320                 self.py, self.noise_matrix, self.inverse_noise_matrix, \
    321                 self.confident_joint, psx = \
--> 322                     estimate_py_noise_matrices_and_cv_pred_proba(
    323                         X=X,
    324                         s=s,

~\AppData\Roaming\Python\Python38\site-packages\cleanlab\latent_estimation.py in estimate_py_noise_matrices_and_cv_pred_proba(X, s, clf, cv_n_folds, thresholds, converge_latent_estimates, py_method, seed)
    697       joint count matrix i.e. confident joint, predicted probability matrix)"""
    698 
--> 699     confident_joint, psx = estimate_confident_joint_and_cv_pred_proba(
    700         X=X,
    701         s=s,

~\AppData\Roaming\Python\Python38\site-packages\cleanlab\latent_estimation.py in estimate_confident_joint_and_cv_pred_proba(X, s, clf, cv_n_folds, thresholds, seed, calibrate)
    608     for k, (cv_train_idx, cv_holdout_idx) in enumerate(kf.split(X, s)):
    609 
--> 610         clf_copy = copy.deepcopy(clf)
    611 
    612         # Select the training and holdout cross-validated sets.

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_tuple(x, memo, deepcopy)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in <listcomp>(.0)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_tuple(x, memo, deepcopy)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in <listcomp>(.0)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_tuple(x, memo, deepcopy)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in <listcomp>(.0)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_tuple(x, memo, deepcopy)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in <listcomp>(.0)
    208 
    209 def _deepcopy_tuple(x, memo, deepcopy=deepcopy):
--> 210     y = [deepcopy(a, memo) for a in x]
    211     # We're not going to put the tuple in the memo, but it's still important we
    212     # check for it, in case the tuple contains recursive mutable structures.

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    170                     y = x
    171                 else:
--> 172                     y = _reconstruct(x, memo, *rv)
    173 
    174     # If is its own copy, don't memoize.

C:\Program Files\Anaconda3\lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    268     if state is not None:
    269         if deep:
--> 270             state = deepcopy(state, memo)
    271         if hasattr(y, '__setstate__'):
    272             y.__setstate__(state)

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    144     copier = _deepcopy_dispatch.get(cls)
    145     if copier is not None:
--> 146         y = copier(x, memo)
    147     else:
    148         if issubclass(cls, type):

C:\Program Files\Anaconda3\lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    228     memo[id(x)] = y
    229     for key, value in x.items():
--> 230         y[deepcopy(key, memo)] = deepcopy(value, memo)
    231     return y
    232 d[dict] = _deepcopy_dict

C:\Program Files\Anaconda3\lib\copy.py in deepcopy(x, memo, _nil)
    159                     reductor = getattr(x, "__reduce_ex__", None)
    160                     if reductor is not None:
--> 161                         rv = reductor(4)
    162                     else:
    163                         reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle '_thread.RLock' object

**Comment by anishathalye** [comment]
#144 adds better handling of situations like this. There is a bug in Cleanlab (that is fixed in #144), but even with that patch, I think there's an issue when your code is used with Cleanlab, because when the `YourFavoriteModel` estimator is cloned, scikit-learn will do a deep copy of the `.model` (a Keras model), and I'm not sure if that's safe to do. See also, #146.

For reference, this is the test code I'm using, based on the code in your issue and filling in some gaps and dummy data:

```python
from tensorflow import keras
from tensorflow.keras.layers import Input, Dropout, Dense
import numpy as np

input_img = Input(shape=(1350,))
x = Dense(units=32, activation='relu')(input_img)
x = Dropout(0.2)(x)
x = Dense(units=10, activation='relu')(x)
x = Dense(units=4, activation='softmax')(x)
model2 = keras.Model(input_img, x)
model2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

from sklearn.base import BaseEstimator

def to_categorical(y, num_classes):
    arr = np.zeros((len(y), num_classes))
    arr[y] = 1
    return arr

class YourFavoriteModel(BaseEstimator): # Inherits sklearn base classifier

    def __init__(self, model):
        self.model = model
    
    def fit(self, X, y):
        yt = to_categorical(y, num_classes=4)
        self.model.fit(X,yt, epochs=20, shuffle=True)
    
    def predict(self, X):
        return np.argmax(self.model.predict(X,axis=-1))

    def predict_proba(self, X):
        return self.model.predict(X)
                     
    def score(self, X, y, sample_weight=None):
        yt = to_categorical(y, num_classes=4)
        return self.model.evaluate(X,yt)[1]

from cleanlab.classification import LearningWithNoisyLabels
lnl = LearningWithNoisyLabels(clf=YourFavoriteModel(model2), n_jobs=1)

X_train = np.random.uniform(size=(100, 1350))
y_train = np.random.randint(0, 4, size=100)

lnl.fit(X_train, y_train)
```

I think you should modify the code to look something like this, so that `YourFavoriteModel` is correctly clonable:

```python
from tensorflow import keras
from tensorflow.keras.layers import Input, Dropout, Dense
import numpy as np

def make_model():
    input_img = Input(shape=(1350,))
    x = Dense(units=32, activation='relu')(input_img)
    x = Dropout(0.2)(x)
    x = Dense(units=10, activation='relu')(x)
    x = Dense(units=4, activation='softmax')(x)
    model = keras.Model(input_img, x)
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

from sklearn.base import BaseEstimator

def to_categorical(y, num_classes):
    arr = np.zeros((len(y), num_classes))
    arr[y] = 1
    return arr

class YourFavoriteModel(BaseEstimator): # Inherits sklearn base classifier

    def __init__(self):
        self.model = make_model()
    
    def fit(self, X, y):
        yt = to_categorical(y, num_classes=4)
        self.model.fit(X,yt, epochs=20, shuffle=True)
    
    def predict(self, X):
        return np.argmax(self.model.predict(X,axis=-1))

    def predict_proba(self, X):
        return self.model.predict(X)
                     
    def score(self, X, y, sample_weight=None):
        yt = to_categorical(y, num_classes=4)
        return self.model.evaluate(X,yt)[1]

from cleanlab.classification import LearningWithNoisyLabels
lnl = LearningWithNoisyLabels(clf=YourFavoriteModel(), n_jobs=1)

X_train = np.random.uniform(size=(100, 1350))
y_train = np.random.randint(0, 4, size=100)

lnl.fit(X_train, y_train)
```
