### ISSUE TITLE
RuntimeWarning: invalid value encountered in clip_range (vectorized)

### ISSUE THREAD

**Issue by hafiz031** [cleanlab/cleanlab#88]
While running `cleanlab.latent_estimation.estimate_cv_predicted_probabilities` I get the following warning:

```
/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/cleanlab/latent_estimation.py:431: RuntimeWarning: invalid value encountered in true_divide
  noise_matrix = confident_joint / y_count
/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/cleanlab/latent_algebra.py:247: RuntimeWarning: invalid value encountered in true_divide
  py = inverse_noise_matrix.diagonal() / noise_matrix.diagonal() * ps
/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in clip_range (vectorized)
  outputs = ufunc(*inputs)
/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/numpy/lib/function_base.py:2246: RuntimeWarning: invalid value encountered in clip_noise_rate_range (vectorized)
  outputs = ufunc(*inputs)
```

This doesn't happen always, I tried with different data (actually a sub-sample of the whole data), in that case (sub-sample) this warning doesn't show up. But when I am trying to run it with my whole data-set, I am getting this warning again.

I am measuring the performance with `f1_score`:
```
f1_score(y, np.argmax(pyx, axis = 1), average = "macro")
```

Probably the most important observation here is that, when this warning occurs, the `f1_score` becomes too low (around `0.02`). But when it doesn't occur the `f1_score` seems to be healthy (around `0.9`).

**Comment by hafiz031** [comment]
Anyway, the I have figured out the root cause behind low score. It was because of not shuffling the data. The `Fasttext` API provided by `cleanlab` doesn't do it of its own. So, it is our responsibility to shuffle the data beforehand.

**Comment by anishathalye** [comment]
Thank you for reporting back on your findings! We would have updated the documentation, but we have decided as of 0.0.12 to drop integrated support for fastText.
