### ISSUE TITLE
ValueError: shape mismatch: value array of shape (7608,34) could not be broadcast to indexing result of shape (7608,40)

### ISSUE THREAD

**Issue by hafiz031** [cleanlab/cleanlab#89]
Following is the full error which I am getting.

```
Traceback (most recent call last):
  File "cleanit.py", line 212, in <module>
    cit.train()
  File "cleanit.py", line 114, in train
    pyx = cleanlab.latent_estimation.estimate_cv_predicted_probabilities(
  File "/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/cleanlab/latent_estimation.py", line 782, in estimate_cv_predicted_probabilities
    return estimate_py_noise_matrices_and_cv_pred_proba(
  File "/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/cleanlab/latent_estimation.py", line 722, in estimate_py_noise_matrices_and_cv_pred_proba
    confident_joint, psx = estimate_confident_joint_and_cv_pred_proba(
  File "/home/hafiz031/text-data-cleanup/venv/lib/python3.8/site-packages/cleanlab/latent_estimation.py", line 641, in estimate_confident_joint_and_cv_pred_proba
    psx[cv_holdout_idx] = psx_cv
ValueError: shape mismatch: value array of shape (7608,34) could not be broadcast to indexing result of shape (7608,40)
```

It seems to be that, this issue is related to cross validation. I have used `10` fold cross validation. I can ensure that each of my training classes has at least more than `10` examples (The smallest class has `41` examples and the largest class has `16329` examples. It is an imbalanced text data-set). I am using `FastText` classifier for this purpose (`from cleanlab.models.fasttext import FastTextClassifier`). 

I have printed out the some relevant values. I have in total `40` classes. In which iterations no error happens, it prints something like the following:
```
psx.shape: (76075, 40)
X_train_cv: (68467,)
X_holdout_cv: (7608,)
s_train_cv: (68467,)
s_holdout_cv: (7608,)
Read 0M words
Number of words:  21226
Number of labels: 40
Progress: 100.0% words/sec/thread:  139464 lr:  0.000000 avg.loss:  0.144096 ETA:   0h 0m 0s
```
But when error occurs, just before throwing error the following is getting printed (please note that the number of labels is `34`, although it should be `40`:
```
X_train_cv: (68467,)
X_holdout_cv: (7608,)
s_train_cv: (68467,)
s_holdout_cv: (7608,)
Read 0M words
Number of words:  13351
Number of labels: 34
Progress: 100.0% words/sec/thread:  199996 lr:  0.000000 avg.loss:  0.181697 ETA:   0h 0m 0s
```

Just after that, the error is being thrown.

I have skim thrown the implementation (`latent_istimation.py`) inside the `cleanlab` library, where I have found it is using `StratifiedKFold`. From my understanding as in my case the smallest class also has more (or equal) number of examples than the number of cross validations. So, technically this problem should not occur. Why this is happening then?

**Comment by jwmueller** [comment]
Sorry your question got overlooked. If this issue has not been resolved in recent releases of cleanlab (like 2.1.0), then have you considered just implementing the cross-validation yourself?  

You can always ensure yourself that all classes appear in the training split of each cross-validation fold.  If this is not being ensured by sklearn's StratifiedKFold, then something may be wrong about how your labels are formatted.

**Comment by hafiz031** [comment]
@jwmueller actually as I can remember I didn't implement any cross validation myself. I used `pyx = cleanlab.latent_estimation.estimate_cv_predicted_probabilities()` which takes relevant parameters according to the documentation. I just ensured the smaller class also has more or equal number of examples than the cross validation count.
Also, don't forget to shuffle your data before passing to this method, this method doesn't do it automatically as I found when the last time I worked on it.

**Comment by jwmueller** [comment]
I was suggesting if our cross-validation doesn't work for you for some odd reason, you could implement the cross-validation yourself.  

Thanks for the info though! I've tested the (latest version of the) code in the relevant lower-level function which is:
`estimate_confident_joint_and_cv_pred_proba()` 
https://docs.cleanlab.ai/stable/_modules/cleanlab/count.html#estimate_confident_joint_and_cv_pred_proba

and it seems to work fine. Specifically our key code-block is:
```
kf = StratifiedKFold(n_splits=cv_n_folds, shuffle=True, random_state=seed)

for k, (cv_train_idx, cv_holdout_idx) in enumerate(kf.split(X=labels, y=labels)):
    X_train_cv, X_holdout_cv, s_train_cv, s_holdout_cv = train_val_split(
            X, labels, cv_train_idx, cv_holdout_idx
        )
```

For me this code does indeed create stratified splits and it also does shuffle the dataset properly to determine the indices in `cv_train_idx` for each fold (ie. these are not simply consecutive indices).
