### ISSUE TITLE
[CI] make the unit tests run in order from faster -> slower

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#890]
Also put the unit tests that cover less commonly updated / rare functionality closer to the end of the order. 

Also make sure CI job fails early as soon as a unit test fails, rather than still running the rest of the unit tests

**Comment by tataganesh** [comment]
Some pointers for future reference - 

* The  [pytest_collection_modifyitems](https://docs.pytest.org/en/latest/reference/reference.html#pytest.hookspec.pytest_collection_modifyitems) hook allows modification of test execution order. Tests can be ordered based on module/class/function. For the CI job, a [flag](https://stackoverflow.com/a/60155675/8505509) can be added for reordering. 

* pytest's `-x` flag can be used to [stop after first failure](https://docs.pytest.org/en/6.2.x/usage.html#stopping-after-the-first-or-n-failures).

**Comment by tataganesh** [comment]
Summary of brief discussion with @elisno regarding a possible first approach (does not cover the full scope of this issue). 

* Determine k slowest tests (e.g. 5-10) and use [pytest_collection_modifyitems](https://docs.pytest.org/en/latest/reference/reference.html#pytest.hookspec.pytest_collection_modifyitems) to move the slowest tests at the end of the test-execution order. Add a pytest flag to optionally perform this reordering ( We will use this flag for the CI). 
* Use pytest's `maxfail`  flag to stop the testing processing after 3 failed tests.
