### ISSUE TITLE
Can you share tutorial on how to do Label Error Detection using Ultralytics YOLOv8?

### ISSUE THREAD

**Issue by cgokce** [cleanlab/cleanlab#891]
Hello, firstly thanks for sharing this great project as open source. 

I have looked into your label error detection tutorial [using Detectron model ](https://docs.cleanlab.ai/stable/tutorials/object_detection.html)and want to use the similar pipeline for label error detection using YOLOv8 model and my custom dataset.
 
Would you provide similar tutorial on how to run the label error detection pipeline using Ultralytics Yolov8?

**Comment by jwmueller** [comment]
Have you looked at this notebook:  https://github.com/cleanlab/examples/blob/master/object_detection/detectron2_training-kfold.ipynb

which shows how to train & inference the object detection model for use with cleanlab?

Should be similar to do this with your own object detection model, you just need to follow a tutorial that Ultralytics provides to run their object detection model and finally reformat its predictions to match the format expected by cleanlab.  If you have questions about Ultralytics, it will be better to ask their team (I am not familiar)

**Comment by tataganesh** [comment]
@cgokce If you are still looking for a some resources, here is a [simple notebook](https://www.kaggle.com/code/tataganesh/auditing-face-mask-dataset-using-cleanlab-part-2/notebook) for label error detection using YoloV8 on a Face-Mask Detection Dataset.

**Comment by jwmueller** [comment]
feel free to reopen this if you still have questions
