### ISSUE TITLE
Why can't I find the pruning module in the new version?

### ISSUE THREAD

**Issue by 51057913** [cleanlab/cleanlab#904]
I want to import pruning in my model to use get_noise_indices,but it shows the pruning module does not exist.
```
 from cleanlab.pruning import get_noise_indices
ModuleNotFoundError: No module named 'cleanlab.pruning'

```

**Comment by jwmueller** [comment]
You are using an outdated version of the package. 

This `cleanlab.pruning` module has been long removed from the package. You can find the documentation for the most recent stable release (installed via `pip install cleanlab --upgrade`) here:  https://docs.cleanlab.ai/

Here's a migration guide for updating your old code:  https://docs.cleanlab.ai/v2.3.0/migrating/migrate_v2.html
(note this migration guide is from v2.3.0 docs, whereas we're now on v2.5.0, but v2.5.0 is backwards compatible with v2.3.0)

**Comment by 51057913** [comment]
> You are using an outdated version of the package.
> 
> This `cleanlab.pruning` module has been long removed from the package. You can find the documentation for the most recent stable release (installed via `pip install cleanlab --upgrade`) here: https://docs.cleanlab.ai/
> 
> Here's a migration guide for updating your old code: https://docs.cleanlab.ai/v2.3.0/migrating/migrate_v2.html (note this migration guide is from v2.3.0 docs, whereas we're now on v2.5.0, but v2.5.0 is backwards compatible with v2.3.0)

Thank you! It's very useful to me!

**Comment by jwmueller** [comment]
I assume this ^ addressed your question.  
Feel free to ask any other questions you have by re-opening this issue or in a new one!
