### ISSUE TITLE
Add underperforming_group issue type among the Datalab defaults 

### ISSUE THREAD

**Issue by tataganesh** [cleanlab/cleanlab#910]
Test issue manager with different datasets (Image, tabular etc.) to make sure that the underperforming group in the dataset is extracted successfully.  List any failure cases that might need to be addressed before adding this issue type to the defaults.

**Comment by jwmueller** [comment]
first add extra step that `is_issue = True` only if the cluster in question contains at least M datapoints, for say M = 10

**Comment by jwmueller** [comment]
dont forget to update the datalab documentation listing the default issue types
