### ISSUE TITLE
add `show_all_issues` optional argument to: datalab.report()

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#922]
This arg has default = False. 
If True, the report includes issue types with `num_issue = 0` in the Datalab report, otherwise we suppress such issues from the report.
This is critical to ensure the report doesn't get overwhelming as more issue-types are supported 

Also: `datalab.report()` docstring is missing documentation for the argument:
`show_summary_score` 

Add it while adding this other argument.

**Comment by nayan2167** [comment]
Hi @jwmueller I am working on this ✌️
