### ISSUE TITLE
How to use find_label_issues function in AWS sagemaker?

### ISSUE THREAD

**Issue by sschangi** [cleanlab/cleanlab#938]
Hi,

I am trying to use the `find_label_issues` function in AWS SageMaker. After conducting some research, I came across this notebook: https://github.com/cleanlab/aws-marketplace/blob/main/label-inspector/label_inspector.ipynb, as well as this AWS Marketplace page: https://aws.amazon.com/marketplace/pp/prodview-en3c45ncm5som. Both seem to suggest using Cleanlab through AWS Marketplace. I am wondering if there's a more straightforward way to use the `find_label_issues` function directly in SageMaker?

Thanks,
Saeed

**Comment by jwmueller** [comment]
responded to same question asked in the [Cleanlab Community Slack](https://cleanlab.ai/slack)
