### ISSUE TITLE
is_label_issue = False but given_label != predicted_label

### ISSUE THREAD

**Issue by tqdo** [cleanlab/cleanlab#941]
Is it expected that there are cases where `is_label_issue = False` but `given_label != predicted_label`. I can provide the code if this behavior is unexpected and the code is needed for debugging. Thanks

![Screenshot 2024-01-03 at 11 38 53 PM](https://github.com/cleanlab/cleanlab/assets/53948469/2e6687be-8ad1-4704-b199-4f6d44d2e626)

**Comment by jwmueller** [comment]
Yes this is expected, not a bug. The predicted label is simply the prediction from your ML model. 

Cleanlab is not just measuring whether your ML model prediction disagrees with the given label to diagnose label errors. The Confident Learning algorithm we are using is much better:

https://arxiv.org/abs/1911.00068
