### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by BastianZim** [cleanlab/cleanlab#95]
Hi, the _setup.py_ lists `GPLv3+` (Which would be _GNU GENERAL PUBLIC LICENSE_ )as the current license but the actual license has the text of _GNU Affero General Public License v3.0 only (`AGPL-3.0-only`)_ and is recognised as such by Github. Which license is the correct one?

Thanks!

Ref: https://spdx.org/licenses/

**Comment by anishathalye** [comment]
Hi! It's AGPLv3 right now (setup.py is out of date). If the distinction between GPLv3 and AGPLv3 matters for your particular use case, could you let us know what exactly you're doing / why it matters? If you don't want to post that in this public issue, feel free to email me (anish@cleanlab.ai).

**Comment by BastianZim** [comment]
Ahh that's fine but thanks for the offer, I just stumbled upon this when checking https://github.com/cleanlab/cleanlab/issues/24 but I'm fine with either license. :)
