### ISSUE TITLE
In object detection tutorial, showcase how we can use the exploratory methods to manually detect anomalies

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#951]
Showcase the use of these functions from [object_detection.summary](https://github.com/cleanlab/cleanlab/blob/master/cleanlab/object_detection/summary.py) near the end of [the tutorial](https://docs.cleanlab.ai/master/tutorials/object_detection.html) in a section titled:

## Summarizing dataset annotations

This section showcases techniques to detect other annotation irregularities based on exploratory data analysis that does not depend on any ML model.
...

Functions to showcase (showcase most anomalous images in the dataset from each method's output):

bounding_box_size_distribution

object_counts_per_image

class_label_distribution

**Comment by aditya1503** [comment]
There were no issues I could find from using these functions, the anomalies that were detected were just close-up photographs of objects which have large areas, which aren't issues

**Comment by aditya1503** [comment]
> @aditya1503 so you think it's not worth showcasing these methods?
> 
> I don't think this method needs to reveal issues in the tutorial dataset. Rather we just need to showcase it somewhere, otherwise no user will ever know this method exists...
> 
> So I'd just showcase it's use and show minimal results from it. I.e. keep the new final section of the tutorial notebook as short as possible.

https://github.com/cleanlab/examples/pull/88 I've added here

**Comment by jwmueller** [comment]
addressed in https://github.com/cleanlab/cleanlab/pull/969
