### ISSUE TITLE
Datalab equivalent for Regression?

### ISSUE THREAD

**Issue by tqdo** [cleanlab/cleanlab#967]
I wonder whether Cleanlab has something for regression problems that is equivalent to Datalab? Datalab's find_issues function requires `pred_probs`, which is not applicable for regression problems. I really like Datalab because it shows all key issues conveniently. Thanks

**Comment by jwmueller** [comment]
Hi @tqdo , yes doing regression tasks with Datalab already exists in the latest developer version.

```
pip install "git+https://github.com/cleanlab/cleanlab.git#egg=cleanlab[all]"
```

https://docs.cleanlab.ai/master/cleanlab/datalab/datalab.html
Note the `task` argument in Datalab (you can set it to 'regression')

We have a tutorial for using this in the works here:
https://github.com/cleanlab/cleanlab/pull/966

Would appreciate your feedback!

**Comment by jwmueller** [comment]
the tutorial is currently in the works not yet published. You can follow along with our progress in the linked PR. 

More precisely, the current working version of it is here (which you should be able to run today as long as you install the developer version of cleanlab):

https://github.com/cleanlab/cleanlab/blob/6811d14acb849a99699e3ff5e7f90967d8747bc2/docs/source/tutorials/regression.ipynb

**Comment by jwmueller** [comment]
actually all of those capabilities are already available! That's why we extended Datalab to work for multi-label and regression tasks. 

This is not demonstrated in the current tutorials yet, but after you run `datalab.find_issues(...)` for a regression or [multi-label](https://docs.cleanlab.ai/master/tutorials/multilabel_classification.html) task, it will detect all of the types of data issues featured in our datalab quickstart tutorial:

https://docs.cleanlab.ai/master/tutorials/datalab/datalab_quickstart.html

**Comment by elisno** [comment]
Hi @tqdo!
Thank you for pointing this out!

At the moment, on the latest developer version, `Datalab(..., task="regression")` is only configured to find label issues (specifically for this task).

I've got a PR in the making that should open this weekend. That includes the issues checks for a regression task:
- Outlier detection
- (near) duplicate detection
- Non-IID check
- Null-value check.

I'll ping you here again when you can try it out again in Colab.

**Comment by jwmueller** [comment]
Hi @tqdo, sorry I gave you the pointer a bit too early, but now in the latest release: cleanlab v2.6.0, the original tip will now do what you wanted:

Link to the tutorial:  https://docs.cleanlab.ai/stable/tutorials/regression.html#5.-Other-ways-to-find-noisy-labels-in-regression-datasets

You can `pip install --upgrade cleanlab` to start using v2.6.0.

> After you run datalab.find_issues(...) for a regression task, it will detect all of the types of data issues featured in our datalab quickstart tutorial: https://docs.cleanlab.ai/master/tutorials/datalab/datalab_quickstart.html
> 
> Just delete the optional issue_types argument from the call to lab.find_issues(...) which in our tutorials is restricting Datalab to only check for label issues.

**Comment by elisno** [comment]
Good to hear @tqdo!
The same support for multi-label was added to Datalab in the latest release. Check out the [updated tutorial](https://docs.cleanlab.ai/stable/tutorials/multilabel_classification.html) for multi-label classification.
