### ISSUE TITLE
create user-facing cleanlab.data_valuation module

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#973]
Move the following method to the cleanlab.data_valuation module, such that it can be a standalone user-facing method:

[cleanlab.datalab.internal.issue_maanger.data_valuation._knn_shapley_score
](https://docs.cleanlab.ai/master/_modules/cleanlab/datalab/internal/issue_manager/data_valuation.html#DataValuationIssueManager.find_issues)

**Comment by 01PrathamS** [comment]
To clarify, are we currently in the process of moving the private method ```_knn_shapely_score``` to the ```DataValuationIssueManager``` class to make it a standalone user-facing method under the ```data_valuation.py``` module?

**Comment by jwmueller** [comment]
@01PrathamS The goal of this GH issue is to make this move. 

I'd name the public method `cleanlab.data_valuation.data_shapely(labels, features: None, knn_graph: None, k=10)`

and internally the method should look something like:

```
if knn_graph is not None and features is not None:
    raise ValueError(...)

if knn_graph is None:
    knn_graph = reuse existing helper methods in datalab to build KNN graph from the features vector

return _knn_shapley_score(knn_graph, labels, k)
```

**Comment by coding-famer** [comment]
I think #928 is quite related to this issue, maybe it's better to start from that?

**Comment by jwmueller** [comment]
@coding-famer yep! you probably easily address both at once given you created all of this code :)

**Comment by coding-famer** [comment]
> @coding-famer yep! you probably easily address both at once given you created all of this code :)

Sure, if you @01PrathamS are interested in these two issues, I'm glad to work with you.

**Comment by 01PrathamS** [comment]
Thank you @coding-famer for taking me into consideration, it's been great to work on this..
