### ISSUE TITLE
Calling Datalab.get_issues() when there are no issues throws an error

### ISSUE THREAD

**Issue by ulya-tkch** [cleanlab/cleanlab#986]
When finding issues using code below (on a dataset where there are no issues), the following attempts (1,2) throw error:

```python
lab = cleanlab.Datalab(data=train[numerical], label_name="label", task="regression")
lab.find_issues(pred_probs=y_train_pred)
```
1.`label_quality_scores = lab.get_issues('label')['label_issues']`
2.`label_quality_scores = lab.get_issues('label')`

Instead should print something like "There are no isses"

**Comment by elisno** [comment]
After some discussion @ulya-tkch and I agreed the first point is not an issue, but a KeyError that is properly handled by Pandas.

The second point is a valid issue, except it's for cases when the `Datalab.issues` dataframe was actually empty. That usually means that either `find_issues` didn't look for the issue (skipped it or wasn't called in the first place) or it failed running that check.

Raising an error in this case in `lab.get_issues` is still the right approach. The error messages have been updated to address this actual issue.

I've also made sure that "on a (regression) dataset where there are no (label) issues", that the `get_issues` method actually works.
I've also tested that the exceptions are actually raised for the empty arrays.
