### ISSUE TITLE
[class / predprobs order for datalab needs to be clarified]

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/cleanlab#991]
In the documentation of pred_probs  for multi-class and multi-label classification Datalabs.

Also add a sentence about how to order pred_probs to the QuickStart tutorial for Datalab and the multilabel tutorial.

**Comment by jwmueller** [comment]
also ensure datalab applies a default sort order to the class ordering for multi-label datasets

**Comment by elisno** [comment]
Closed by #997
